opencomputeproject/OpenNetworkLinux

docs/Building.md
Initial building document for OpenNetworkLinux
=> Initial Building.md Document

make/kbuild.mk, packages/base/any/kernels/3.2.65-1+deb7u2/kconfig.mk
This modification allows for kernels other than 3.x to be built.
=> Modified kbuild to allow for a kernel major version to set

packages/platforms/accton/x86-64-accton-as5712-54x/platform-config/r0/src/python/x86_64_accton_as5712_54x_r0/__init__.py, packages/platforms/accton/x86-64-accton-as6712-32x/platform-config/r0/src/python/x86_64_accton_as6712_32x_r0/__init__.py
Adapted version of the ONL pull request https://github.com/opennetworklinux/ONL/pull/175/files
=> AS5712-54x DC Power Addition

packages/platforms/quanta/x86-64-quanta-ly6-rangeley/platform-config/Makefile, packages/platforms/quanta/x86-64-quanta-ly6-rangeley/platform-config/r0/Makefile, packages/platforms/quanta/x86-64-quanta-ly6-rangeley/platform-config/r0/PKG.yml, packages/platforms/quanta/x86-64-quanta-ly6-rangeley/platform-config/r0/src/lib/boot/grub.cfg, packages/platforms/quanta/x86-64-quanta-ly6-rangeley/platform-config/r0/src/lib/boot/x86-64-quanta-ly6-rangeley-r0, packages/platforms/quanta/x86-64-quanta-ly6-rangeley/platform-config/r0/src/lib/install/x86-64-quanta-ly6-rangeley-r0.sh, packages/platforms/quanta/x86-64-quanta-ly6-rangeley/platform-config/r0/src/python/x86-64-quanta-ly6-rangeley-r0/__init__.py
Not 100% sure on the def baseconfig(self): part in the __init__.py
=> Initial support for Quanta LY6 Rangeley platform

packages/base/any/initrds/buildroot/builds/buildroot.config-powerpc, packages/base/any/initrds/buildroot/builds/buildroot.config-x86_64, setup.env
set primary mirror only in buildroot configuration files
=> updated buildroot primary mirror to github

.bashrc
Exit explicitly when running in autobuild mode.
=> Attempt to exit.

docker/images/builder7/1.1/Dockerfile, docker/images/builder7/1.1/Makefile, docker/images/builder8/1.1/Dockerfile, docker/images/builder8/1.1/Makefile, docker/tools/onlbuilder
New docker images deployed to hub.docker and tested on machine that previously failed due to issues with binfmt.
=> updated onlbuilder7/8 to v1.1 adding new programs

builds/any/rootfs/jessie/common/common-packages.yml, builds/any/rootfs/wheezy/common/common-packages.yml
@sonoble @rohitmalaga Adding oom-shim to the list of stuff that gets installed by default.
=> Added oom-shim to list of packages to install by default

packages/base/any/oom-shim/src/module/src/oom_shim.c
For OOM OCP demo.
@sonoble @rohitmalaga
=> OOM-SHIM: Read page A2 from dom

packages/base/any/oom-shim/src/module/src/oom_shim.c
=> oom-shim: commented out stray debug statement

packages/base/any/kernels/3.2.65-1+deb7u2/patches/platform-accton-as5812_54x-device-drivers.patch, packages/platforms/accton/x86-64/x86-64-accton-as7712-32x/onlp/builds/src/module/src/fani.c, packages/platforms/accton/x86-64/x86-64-accton-as7712-32x/onlp/builds/src/module/src/platform_lib.h, packages/platforms/accton/x86-64/x86-64-accton-as7712-32x/onlp/builds/src/module/src/psui.c, packages/platforms/accton/x86-64/x86-64-accton-as7712-32x/onlp/builds/src/module/src/sysi.c, packages/platforms/accton/x86-64/x86-64-accton-as7712-32x/onlp/builds/src/module/src/thermali.c, packages/platforms/accton/x86-64/x86-64-accton-as7712-32x/platform-config/r0/src/python/x86_64_accton_as7712_32x_r0/__init__.py
- Fix PSU show unsupported issue
- Modify thermal description
- Add CPU core and lm75(0x4B) temperature sensor
=> [as7712_32x] Add temp sensor(0x4b, CPU core) to onlp and fix PSU unsupported issue.

README.md, docs/SupportedHardware.md
Fixed spelling issues and updated OpenNSL/OFDPA support.
=> Added Accton AS4610 to HCL

tools/autobuild/install.sh
=> updated install.sh to reference new location of version files

setup.env
=> add default RELEASE directory to setup.env

builds/any/installer/installer.sh.in, packages/base/all/vendor-config-onl/src/lib/install/lib.sh, packages/base/all/vendor-config-onl/src/python/onl/install/BaseInstall.py
Reviewer: @jnealtowns @sonoble
=> Updates for larger disks with non-default block sizes

builds/any/installer/installer.sh.in, packages/base/all/vendor-config-onl/src/lib/install/lib.sh
=> Add missing ONIE label-finder, fix bugs in blkid scanner

builds/any/rootfs/jessie/common/all-base-packages.yml, builds/any/rootfs/wheezy/common/all-base-packages.yml
=> Add tcpdump and strace to base packages.

packages/base/all/vendor-config-onl/src/python/onl/platform/base.py
=> Do not show CRC under System Information for "show version"

packages/platforms/agema/Makefile, packages/platforms/agema/vendor-config/Makefile, packages/platforms/agema/vendor-config/PKG.yml, packages/platforms/agema/vendor-config/src/python/agema/__init__.py, packages/platforms/agema/x86-64/Makefile, packages/platforms/agema/x86-64/x86-64-agema-agc7648/Makefile, packages/platforms/agema/x86-64/x86-64-agema-agc7648/onlp/Makefile, packages/platforms/agema/x86-64/x86-64-agema-agc7648/onlp/PKG.yml, packages/platforms/agema/x86-64/x86-64-agema-agc7648/platform-config/Makefile, packages/platforms/agema/x86-64/x86-64-agema-agc7648/platform-config/r0/Makefile, packages/platforms/agema/x86-64/x86-64-agema-agc7648/platform-config/r0/PKG.yml, packages/platforms/agema/x86-64/x86-64-agema-agc7648/platform-config/r0/src/lib/x86-64-agc7648-r0.yml, packages/platforms/agema/x86-64/x86-64-agema-agc7648/platform-config/r0/src/python/x86_64_agc7648_r0/__init__.py
=> Platform x86-64-agema-agc7648 without ONLP

packages/platforms/alphanetworks/x86-64-alphanetworks-snx60a0-486f/platform-config/r0/src/lib/x86-64-alphanetworks-snx60a0-486f-r0.yml
Fixing the console port
@sonoble
=> Platform x86-64-alphanetworks-snx60a0-486f-r0

packages/base/any/onlp/src/onlplib/module/inc/onlplib/i2c.h, packages/base/any/onlp/src/onlplib/module/src/i2c.c
=> support SMBus block read

packages/base/all/vendor-config-onl/src/bin/pylegacy, packages/base/all/vendor-config-onl/src/python/onl/install/App.py, packages/base/all/vendor-config-onl/src/python/onl/install/Fit.py, packages/base/all/vendor-config-onl/src/python/onl/install/InstallUtils.py, packages/base/all/vendor-config-onl/src/python/onl/install/Legacy.py, packages/base/all/vendor-config-onl/src/python/onl/install/ShellApp.py
- don't parse the onie initrd for u-boot systems
- in any case, add legacy u-boot image support so that onie-shell works
=> Added support for legacy u-boot images, see SWL-3462

packages/platforms/accton/powerpc/powerpc-accton-as5710-54x/onlp/builds/src/module/src/platform_lib.h, packages/platforms/accton/powerpc/powerpc-accton-as5710-54x/onlp/builds/src/module/src/sfpi.c
=> add onlp_sfpi_dev_read[write] api support

packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/onlp/builds/src/module/src/sfpi.c, packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/onlp/builds/src/module/src/sfpi.c
=> support onlp_sfpi_dev_read[write] api in as5712, as5812-54x

builds/any/installer/grub/builds/Makefile, builds/any/installer/installer.sh.in, builds/any/installer/sample-postinstall.py, builds/any/installer/sample-postinstall.sh, builds/any/installer/sample-preinstall.py, builds/any/installer/sample-preinstall.sh, builds/any/installer/uboot/builds/Makefile, packages/base/all/vendor-config-onl/src/python/onl/install/BaseInstall.py, packages/base/all/vendor-config-onl/src/python/onl/install/Plugin.py, tools/mkinstaller.py
Ready for review. API has been updated as per review feedback.
Neither of you have seen this code yet, I'm interested in design feedback first to make sure this actually addresses the problem we are trying to solve.
=> pre- and post-install hooks for ONL installer

packages/base/all/vendor-config-onl/src/python/onl/install/App.py, packages/base/all/vendor-config-onl/src/python/onl/install/InstallUtils.py, packages/base/all/vendor-config-onl/src/python/onl/install/ShellApp.py, packages/base/all/vendor-config-onl/src/python/onl/install/SystemInstall.py
- fix enter/exit actions for initrd manipulation code
- fix handling error codes
=> Fix system upgrade, see SWL-3496

packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/fani.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/ledi.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/psui.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/thermali.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/fani.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/ledi.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/platform_lib.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/psui.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/thermali.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/fani.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/ledi.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/platform_lib.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/psui.c, packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/thermali.c
Signed-off-by: Michael Shych <michaelsh@mellanox.com>
=> Changes in usage of onlp_file_read/onlp_file_write APIs.

docs/mibs/OCP-ONL-RESOURCE-MIB.txt, packages/base/any/onlp-snmpd/APKG.yml, packages/base/any/onlp-snmpd/bin/onl-snmp-mpstat, packages/base/any/onlp-snmpd/builds/Makefile, packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/auto/onlp_snmp.yml, packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/inc/onlp_snmp/onlp_snmp_config.h, packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_config.c, packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_platform.c
=> Add CpuAllPercentUtilization and CpuAllPercentIdle.

docs/SupportedHardware.md
ORC is depreciated, will replace with SR, FBOSS, etc.
=> Remove ORC from supported

packages/platforms/celestica/x86-64/x86-64-cel-seastone/Makefile, packages/platforms/celestica/x86-64/x86-64-cel-seastone/onlp/Makefile, packages/platforms/celestica/x86-64/x86-64-cel-seastone/onlp/PKG.yml, packages/platforms/celestica/x86-64/x86-64-cel-seastone/platform-config/Makefile, packages/platforms/celestica/x86-64/x86-64-cel-seastone/platform-config/r0/Makefile, packages/platforms/celestica/x86-64/x86-64-cel-seastone/platform-config/r0/PKG.yml, packages/platforms/celestica/x86-64/x86-64-cel-seastone/platform-config/r0/src/lib/x86-64-cel-seastone-r0.yml, packages/platforms/celestica/x86-64/x86-64-cel-seastone/platform-config/r0/src/python/x86_64_cel_seastone_r0/__init__.py
```
Celestica seastone without ONLP
```
=> Platform Celestica Seastone

packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_platform.c
=> Call pclose after processing mpstat output.

packages/platforms/accton/x86-64/x86-64-accton-as7312-54x/onlp/builds/src/module/src/sysi.c
Update new thermal plan for fan speed.
=> Update new thermal plan for fan speed.

docs/Building.md
There was ONL1.0 info in this document.  Removed and updated.
=> Removed old info from Building.md

packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_int.h, packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_module.c, packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_platform.c, packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_sensors.c
Refactor onlp-snmpd platform and sensor handling so that updates happen in a separate thread.
=> Update resources and sensors in separate thread

packages/platforms/quanta/x86-64/x86-64-quanta-ix1-rangeley/onlp/builds/src/x86_64_quanta_ix1_rangeley/module/src/sfpi.c
1. [IX1] Fix unexpected module present issue: Set P3V3_ZQSFP_EN as high directly
=> Quanta IX1 ONLP Update:

packages/base/any/onlp/src/sff/module/src/sff.c, packages/platforms/accton/x86-64/x86-64-accton-as7312-54x/onlp/builds/src/module/src/platform_lib.c, packages/platforms/accton/x86-64/x86-64-accton-as7312-54x/onlp/builds/src/module/src/platform_lib.h
=> as7312 PSU bug fix

packages/platforms/quanta/x86-64/x86-64-quanta-ix1-rangeley/onlp/builds/src/x86_64_quanta_ix1_rangeley/module/src/sysi.c, packages/platforms/quanta/x86-64/x86-64-quanta-ix2-rangeley/onlp/builds/src/x86_64_quanta_ix2_rangeley/module/src/sysi.c, packages/platforms/quanta/x86-64/x86-64-quanta-ly6-rangeley/onlp/builds/src/x86_64_quanta_ly6_rangeley/module/src/sysi.c, packages/platforms/quanta/x86-64/x86-64-quanta-ly8-rangeley/onlp/builds/src/x86_64_quanta_ly8_rangeley/module/src/sysi.c, packages/platforms/quanta/x86-64/x86-64-quanta-ly9-rangeley/onlp/builds/src/x86_64_quanta_ly9_rangeley/module/src/sysi.c
1. Export GPIO of fan direction
=> [Quanta-LY6,LY8,LY9,IX1,IX2] Update ONLP:

packages/base/all/vendor-config-onl/src/python/onl/install/SystemInstall.py
=> Unmount the EFI directory before doing a re-install

packages/platforms/delta/x86-64/x86-64-delta-ag5648/modules/builds/dni_ag5648_psu.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/thermali.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/platform-config/r0/src/python/x86_64_delta_ag5648_r0/__init__.py, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/modules/builds/dni_ag9032v1_psu.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/modules/builds/dni_emc2305.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/fani.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/ledi.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/platform_lib.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/platform_lib.h, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/sysi.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/thermali.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/platform-config/r0/src/python/x86_64_delta_ag9032v1_r0/__init__.py, packages/platforms/delta/x86-64/x86-64-delta-agc7648a/onlp/builds/src/module/src/sysi.c
This is a pull request for bugfix for Delta's AG5648, AG9032v1, AGC7648a
=> bugfix for Delta's AG5648, AG9032v1, AGC7648a

packages/base/any/onlp/src/sff/module/inc/sff/8472.h, packages/base/any/onlp/src/sff/module/src/sff.c
=> SFP28 CR type and length fix

packages/platforms/delta/x86-64/x86-64-delta-ag5648/modules/builds/dni_ag5648_psu.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/modules/builds/dni_ag5648_sfp.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/modules/builds/dni_emc2305.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/fani.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/ledi.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/platform_lib.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/platform_lib.h, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/sysi.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/thermali.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/platform-config/r0/src/python/x86_64_delta_ag5648_r0/__init__.py
1. Fixed bug: 1.1 shows the correct percentage speed display on fan
2. modify the corresponding LED capability
Signed-off-by: johnson.lu <johnson.lu@deltaww.com>
=> delta_ag5648

packages/platforms/delta/x86-64/x86-64-delta-agc7648a/modules/builds/agc7648a_dps800ab.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648a/onlp/builds/src/module/src/ledi.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648a/onlp/builds/src/module/src/platform_lib.h, packages/platforms/delta/x86-64/x86-64-delta-agc7648a/onlp/builds/src/module/src/sysi.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648a/platform-config/r0/src/python/x86_64_delta_agc7648a_r0/__init__.py
2. modify the shut down  temperature on thermal sensors
3. modify the corresponding capability of LED on the frnt panel and fan
4. fixed the relative speed of fan and thermal
Signed-off-by: ericdocker <ericth.h.tzeng@gamil.com>
=>  1. fix the wrong display value of PSU

builds/any/installer/installer.sh.in, packages/base/all/vendor-config-onl/src/lib/install/lib.sh, packages/base/all/vendor-config-onl/src/python/onl/install/App.py, packages/base/all/vendor-config-onl/src/python/onl/install/ConfUtils.py, packages/base/all/vendor-config-onl/src/python/onl/install/SystemInstall.py, packages/base/all/vendor-config-onl/src/python/onl/platform/base.py, packages/base/all/vendor-config-onl/src/python/onl/platform/current.py
See https://github.com/opencomputeproject/OpenNetworkLinux/issues/283
- export /etc/machine.conf settings to installer.conf
- better handling of machine.conf bits during onie chroots (debug)
=> Clean up platform detection

packages/base/all/vendor-config-onl/src/python/onl/bootconfig/__init__.py
=> Add setters and getters for dns server and domain in OnlBootConfig.

packages/base/all/initrds/loader-initrd-files/src/bin/swiget
Reviewer: @carlroth
Cc: @jnealtowns
=> Support local file paths with colons

packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/modules/builds/dni_ag9032v1_psu.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/ledi.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/psui.c
2. Modify psui.c for PSU status.
3. Modify ledi.c for fan tray led.
=> [delta_ag9032v1]1. Fix the wrong display value of PSU. 

builds/any/installer/installer.sh.in
The wrong filename was tested for existence.
=> Fix wrong filetest for postinstall.sh

packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/modules/builds/x86-64-accton-as6812-32x-psu.c, packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/onlp/builds/src/module/src/platform_lib.c, packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/onlp/builds/src/module/src/platform_lib.h, packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/onlp/builds/src/module/src/psui.c
Add to support that read PSU serial number for as6812-32x
=> [AS6812-32x] Add to support that read PSU serial number for as6812-32x

packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-fan.c, packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-leds.c, packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-psu.c, packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/onlp/builds/src/module/src/platform_lib.c, packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/onlp/builds/src/module/src/platform_lib.h, packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/onlp/builds/src/module/src/psui.c
Add feature support to read PSU serial number on as5812-54x
=> Add feature support to read PSU serial number on as5812-54x

packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/modules/builds/x86-64-accton-as6812-32x-psu.c
Fix to use correct offset to read psu serial
=> Fix to use correct offset to read psu serial

docs/SupportedHardware.md
Removed HTML formatting
Standardized columns and data
Added all currently supported platforms that we have information for
=> Updating SupportedHardware.md to match new HCL

packages/platforms/accton/x86-64/x86-64-accton-as7312-54x/onlp/builds/src/module/src/ledi.c
Changed at ledi.c:
1. correct LOC led to be amber colored.
3. support onlp_ledi_mode_set() for turning on.
Signed-off-by: roy_lee <roy_lee@accton.com>
=> [onlpdump] Correct LOC led control of as7312-54x

packages/platforms/accton/x86-64/x86-64-accton-as7726-32x/platform-config/r0/src/python/x86_64_accton_as7726_32x_r0/__init__.py
Fix code to let insmod ko drv when init
=> As7726 32x

builds/any/installer/installer.sh.in, packages/base/all/initrds/loader-initrd-files/src/bin/switchroot, packages/base/all/initrds/loader-initrd-files/src/bin/sysinit, packages/base/all/vendor-config-onl/src/lib/install/lib.sh, packages/base/all/vendor-config-onl/src/python/onl/install/BaseInstall.py, packages/base/all/vendor-config-onl/src/python/onl/install/InstallUtils.py, packages/base/all/vendor-config-onl/src/python/onl/upgrade/loader.py
- fixed efivarfs support (preferred over raw sysfs access)
- do a proper partition scan during loader upgrade
=> Fixed broken loader upgrade, see SWL-4234

packages/platforms/accton/x86-64/x86-64-accton-csp9250/onlp/builds/src/module/src/psui.c
Modify onlp_psui_info_get() function to ignore not-support feature in PSU.
=> Modify onlp_psui_info_get to ignore not-support feature in PSU.

packages/base/all/vendor-config-onl/src/python/onl/platform/base.py
=> support S4112F

packages/base/all/vendor-config-onl/src/python/onl/platform/base.py, packages/base/all/vendor-config-onl/src/python/onl/platform/baseconfig.py
=> Suppress dmidecode warnings for KVM systems

packages/base/any/onlp/src/onlp/module/src/psu.c
=> do not display PSU Model if it does not exist

packages/base/any/onlp/src/sff/module/src/sff.c
=> support DELL 4xCU cable with new part number

builds/any/rootfs/jessie/common/all-base-packages.yml, builds/any/rootfs/jessie/standard/standard.yml, builds/any/rootfs/stretch/common/all-base-packages.yml, builds/any/rootfs/stretch/standard/standard.yml, make/config.mk, packages/base/all/initrds/loader-initrd-files/src/bin/switchroot, tools/onl-init-pkgs.py
Signed-off-by: Wataru Ishida <ishida@nel-america.com>
=> Support building systemd based system

docs/Building.md
applied and unified markdown syntax for headings
=> Building.md: markdown syntax cleanup

packages/platforms/accton/x86-64/x86-64-accton-as7312-54xs/onlp/builds/src/module/src/platform_lib.c
=> fix as7312-54xs PSU model display

packages/platforms/accton/x86-64/x86-64-accton-as7326-56x/onlp/builds/src/module/src/sysi.c
Implement thermal plan follow HW SPEC
=> Implement thermal plan follow HW SPEC

packages/platforms/accton/x86-64/x86-64-accton-csp9250/modules/PKG.yml, packages/platforms/accton/x86-64/x86-64-accton-csp9250/modules/builds/x86-64-accton-csp9250-leds.c, packages/platforms/accton/x86-64/x86-64-accton-csp9250/modules/builds/x86-64-accton-csp9250-sfp.c, packages/platforms/accton/x86-64/x86-64-accton-csp9250/platform-config/r0/src/lib/x86-64-accton-csp9250-r0.yml
1.Modify csp9250  drv to support kernel-4.14. 
2. Remove not needed debug log
=> Modify csp9250  drv to support kernel-4.14

packages/base/all/vendor-config-onl/src/python/onl/install/ShellApp.py, packages/base/all/vendor-config-onl/src/python/onl/pki/__init__.py, packages/base/all/vendor-config-onl/src/python/onl/util/__init__.py
=> Cleanups for PKI, mounts points, logging, onie-sysinfo

packages/base/any/kernels/modules/dps850.c, packages/platforms/accton/x86-64/x86-64-accton-as7816-64x/onlp/builds/src/module/src/fani.c, packages/platforms/accton/x86-64/x86-64-accton-as7816-64x/onlp/builds/src/module/src/platform_lib.c, packages/platforms/accton/x86-64/x86-64-accton-as7816-64x/onlp/builds/src/module/src/platform_lib.h, packages/platforms/accton/x86-64/x86-64-accton-as7816-64x/onlp/builds/src/module/src/psui.c, packages/platforms/accton/x86-64/x86-64-accton-as7816-64x/platform-config/r0/src/python/x86_64_accton_as7816_64x_r0/__init__.py
1. Add dps850 to common kernel driver for support delta power
2. Modify onlp driver to support both delta and 3y power in as7816
=> Modify PSU driver to suuport delta and 3y power

packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/fani.c, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/sfpi.c
Strings are now terminated properly.
=> x86-64-delta-ag9032v1 fix -Werror=format-overflow

packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/onlp/builds/src/module/src/fani.c, packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/onlp/builds/src/module/src/ledi.c
Strings are now terminated properly.
=> x86-64-accton-as5712_54x fix -Werror=format-overflow

packages/platforms/delta/x86-64/x86-64-delta-ag5648/modules/builds/dni_ag5648_sfp.c, packages/platforms/delta/x86-64/x86-64-delta-ag5648/onlp/builds/src/module/src/sfpi.c
* Strings are now terminated properly.
* Read correct presence registers.
=> Ag5648 fixup

packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/fani.c
also change the file format from dos to unix
=> correct the fan number

packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/platform_lib.h, packages/platforms/delta/x86-64/x86-64-delta-ag9032v1/onlp/builds/src/module/src/sysi.c
update the ag9032v1  fan's speed table which is related to the  thermal temperature 
Signed-off-by: hans <hans.tseng@deltaww.com>
=> 1. update the the  ag9032v1 fan's speed table

packages/platforms/netberg/x86-64/modules/builds/hardware_monitor.c
platforms: netberg: Implement lm-sensors compatible sysfs ABI
While hardware monitoring module provides access to various sensors it
does not provide such infromation in lm-sensors compatible way.
To do that we need to provide sysfs entries described in Linux Kernel
Documentation/hwmon/sysfs-interface file.
Provide read only access to sensors data as driver implements thermal
policy and fan speed control internally.
Signed-off-by: Sergey Popovich <sergey.popovich@ordnance.co>
=> platforms: netberg: Update hardware monitor driver

packages/platforms/quanta/x86-64/x86-64-quanta-ix7-rglbmc/modules/builds/quanta_platform_ix7.c, packages/platforms/quanta/x86-64/x86-64-quanta-ix7-rglbmc/onlp/builds/src/x86_64_quanta_ix7_rglbmc/module/src/sfpi.c, packages/platforms/quanta/x86-64/x86-64-quanta-ix7-rglbmc/platform-config/r0/src/python/x86_64_quanta_ix7_rglbmc_r0/__init__.py, packages/platforms/quanta/x86-64/x86-64-quanta-ix8-rglbmc/modules/builds/qci_platform_ix8.c, packages/platforms/quanta/x86-64/x86-64-quanta-ix8-rglbmc/onlp/builds/src/x86_64_quanta_ix8_rglbmc/module/src/sfpi.c, packages/platforms/quanta/x86-64/x86-64-quanta-ix8-rglbmc/platform-config/r0/src/python/x86_64_quanta_ix8_rglbmc_r0/__init__.py
[Quanta] change sfp and qsfp driver from 24c02 to oom (IX7, IX8)
=> [Quanta] change sfp and qsfp driver from at24c02 to oom (IX7, IX8)

packages/base/any/onlp/src/onlp/module/inc/onlp/platformi/sfpi.h, packages/base/any/onlp/src/onlp/module/src/sfp.c, packages/base/any/onlp/src/onlp_platform_defaults/module/src/sfpi.c
=> onlp_sfp_dev_read/write API

packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/modules/builds/dni_agc7648sv1_psu.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/fani.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/ledi.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/platform_lib.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/platform_lib.h, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/psui.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/sfpi.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/sysi.c, packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/thermali.c
1.Improve CPU load by reduce IPMITOOL usage
2.Fix psu & led bug in I2C mode
=> Modify agc7648sv1

packages/platforms/accton/x86-64/x86-64-accton-as5916-54xm/onlp/builds/src/module/src/ledi.c, packages/platforms/accton/x86-64/x86-64-accton-as5916-54xm/onlp/builds/src/module/src/sysi.c
For accton As5916_54xm: 
1. Update thermal policy.
2. Enable onlp_ledi_set() to turn on LED.
=> [platform]As5916_54xm: update thermal policy

packages/base/any/kernels/modules/accton_i2c_psu.c, packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/modules/builds/x86-64-accton-as9716-32d-leds.c, packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/onlp/builds/src/module/src/ledi.c, packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/onlp/builds/src/module/src/platform_lib.c, packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/onlp/builds/src/module/src/platform_lib.h, packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/onlp/builds/src/module/src/psui.c, packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/onlp/builds/src/module/src/sysi.c, packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/platform-config/r0/src/python/x86_64_accton_as9716_32d_r0/__init__.py
Add onlp to support 3y power(yesm1300am). Fix LED issue.
=> Add onlp to support 3y power(yesm1300am). Fix LED.

packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/onlp/builds/src/module/src/sysi.c
=> Add as9716-32d thermal plan

packages/base/all/vendor-config-onl/src/python/onl/platform/base.py
=> New OnlPlatformPortConfig for S5212/S5224

packages/platforms/delta/x86-64/x86-64-delta-ag8032/onlp/builds/src/module/src/fani.c, packages/platforms/delta/x86-64/x86-64-delta-ag8032/onlp/builds/src/module/src/platform_lib.c, packages/platforms/delta/x86-64/x86-64-delta-ag8032/onlp/builds/src/module/src/platform_lib.h, packages/platforms/delta/x86-64/x86-64-delta-ag8032/onlp/builds/src/module/src/thermali.c
=> add trace log and update

packages/platforms/accton/x86-64/x86-64-accton-asgvolt64/onlp/builds/src/module/src/platform_lib.c, packages/platforms/accton/x86-64/x86-64-accton-asgvolt64/onlp/builds/src/module/src/platform_lib.h, packages/platforms/accton/x86-64/x86-64-accton-asgvolt64/onlp/builds/src/module/src/sysi.c
=> Fix combo port led issue

packages/platforms/mellanox/x86-64/x86-64-mlnx-msn3800/platform-config/r0/src/python/x86_64_mlnx_msn3800_r0/__init__.py
Fix port number 32->64 for MSN3800 system
=> Fix port number 32->64 for MSN3800 system

packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/fani.c, packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/sysi.c
Reviewer: @jnealtowns @zhouzi88
=> as7726 fan related bug fix

packages/platforms/accton/x86-64/asgvolt64/onlp/builds/x86_64_accton_asgvolt64/module/src/platform_lib.h
Correct system eeprom sysfs path
=> Correct system eeprom sysfs path

packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/platform_lib.c, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/platform_lib.h, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/psui.c, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/sysi.c, packages/platforms/accton/x86-64/as9716_32d/platform-config/r0/src/python/x86_64_accton_as9716_32d_r0/__init__.py
Modify to probe sfp port to use 'optoe2'
=> Modify to probe sfp port to use optoe2

packages/platforms/delta/x86-64/ag9064/modules/PKG.yml, packages/platforms/delta/x86-64/ag9064/modules/builds/Makefile, packages/platforms/delta/x86-64/ag9064/modules/builds/src/Makefile, packages/platforms/delta/x86-64/ag9064/modules/builds/src/client.h, packages/platforms/delta/x86-64/ag9064/modules/builds/src/delta_ag9064_common.h, packages/platforms/delta/x86-64/ag9064/modules/builds/src/delta_ag9064_cpld.c, packages/platforms/delta/x86-64/ag9064/modules/builds/src/delta_ag9064_platform.c, packages/platforms/delta/x86-64/ag9064/modules/builds/src/delta_ag9064_swpld.c, packages/platforms/delta/x86-64/ag9064/modules/builds/src/hbm.h, packages/platforms/delta/x86-64/ag9064/modules/builds/src/hw.h, packages/platforms/delta/x86-64/ag9064/modules/builds/src/i2c-mei_io.c, packages/platforms/delta/x86-64/ag9064/modules/builds/src/i2c-mei_io.h, packages/platforms/delta/x86-64/ag9064/modules/builds/src/i2c-mei_main.c, packages/platforms/delta/x86-64/ag9064/modules/builds/src/i2c-mei_rw.c, packages/platforms/delta/x86-64/ag9064/modules/builds/src/i2c-mei_rw.h, packages/platforms/delta/x86-64/ag9064/modules/builds/src/i2c-mei_type.h, packages/platforms/delta/x86-64/ag9064/modules/builds/src/mei_dev.h, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/fani.c, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/ledi.c, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/platform_lib.c, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/platform_lib.h, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/psui.c, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/sfpi.c, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/sysi.c, packages/platforms/delta/x86-64/ag9064/onlp/builds/x86_64_delta_ag9064/module/src/thermali.c, packages/platforms/delta/x86-64/ag9064/platform-config/r0/src/lib/x86-64-delta-ag9064-r0.yml, packages/platforms/delta/x86-64/ag9064/platform-config/r0/src/python/x86_64_delta_ag9064_r0/__init__.py
Modify Delta AG9064 platform.
1. Add i2c mei driver
2. Add platform driver, cpld driver and swpld driver
3. Update kernel version to 4.9.75
4. Update ONLPI
=> [AG9064] Modify platform driver and ONLPI.

packages/platforms/accton/x86-64/as7926-80xk/modules/builds/x86-64-accton-as7926-80xk-cpld.c, packages/platforms/accton/x86-64/as7926-80xk/onlp/builds/x86_64_accton_as7926_80xk/module/src/sfpi.c, packages/platforms/accton/x86-64/as7926-80xk/platform-config/r0/src/python/x86_64_accton_as7926_80xk_r0/__init__.py
Added two SFP 10G ports support for AS7926_80xk to show in onlpdump after testing on DUT.
[AS7926_80xk_onlpdump_log_10G_SFP.txt.txt](https://github.com/opencomputeproject/OpenNetworkLinux/files/3557985/AS7926_80xk_onlpdump_log_10G_SFP.txt.txt)
=> Added two SFP 10G ports support for AS7926_80xk

packages/platforms/accton/x86-64/asgvolt64/onlp/builds/x86_64_accton_asgvolt64/module/src/sysi.c
Modify to set combo port led via ma1
=> Modify to set combo port led via ma1

packages/platforms/delta/x86-64/agc7646slv1b/onlp/builds/x86_64_delta_agc7646slv1b/module/src/platform_lib.c, packages/platforms/delta/x86-64/agc7646slv1b/onlp/builds/x86_64_delta_agc7646slv1b/module/src/platform_lib.h, packages/platforms/delta/x86-64/agc7646slv1b/onlp/builds/x86_64_delta_agc7646slv1b/module/src/sysi.c, packages/platforms/delta/x86-64/agc7648sv1/onlp/builds/x86_64_delta_agc7648sv1/module/src/platform_lib.h, packages/platforms/delta/x86-64/agc7648sv1/onlp/builds/x86_64_delta_agc7648sv1/module/src/sysi.c
implement onlp_sysi_ioctl() function on delta agc7648sv1 and agc7646slv1b platform
=> implement onlp_sysi_ioctl() function on delta agc7648sv1 and agc7646slv1b platform

packages/base/any/kernels/4.9-lts/patches/0033-mlxsw-minimal-Provide-optimization-for-module-number.patch, packages/base/any/kernels/4.9-lts/patches/0034-mlxsw-minimal-Add-validation-for-FW-version.patch, packages/base/any/kernels/4.9-lts/patches/series
Mellanox:
1. mlxsw-minimal: provide optimization for module number detection
2. Add validation for ASIC FW version
=> Mellanox kernel patches: provide optimization for module number detection

tools/onlpm.py
Signed-off-by: Wataru Ishida <ishida@nel-america.com>
=> onlpm: support more fpm options

packages/platforms/accton/x86-64/as4630-54pe/onlp/builds/x86_64_accton_as4630_54pe/module/src/sysi.c, packages/platforms/accton/x86-64/as4630-54pe/platform-config/r0/src/lib/x86-64-accton-as4630-54pe-r0.yml
1. Add support thermal plan for as4630
2. Set intel_iommu=off
=> Add support thermal plan for as4630

packages/platforms/accton/x86-64/as7712-32x/onlp/builds/x86_64_accton_as7712_32x/module/src/platform_lib.c
=> AS7712 bug fix

packages/platforms/accton/x86-64/asgvolt64/modules/builds/x86-64-accton-asgvolt64-cpld.c, packages/platforms/accton/x86-64/asgvolt64/modules/builds/x86-64-accton-asgvolt64-sys.c, packages/platforms/accton/x86-64/asgvolt64/platform-config/r0/src/python/x86_64_accton_asgvolt64_r0/__init__.py
Add support pon_port led sysfs
=> Add support pon_port led sysfs

packages/platforms/accton/x86-64/asxvolt16/modules/builds/x86-64-accton-asxvolt16-cpld.c, packages/platforms/accton/x86-64/asxvolt16/modules/builds/x86-64-accton-asxvolt16-sfp.c
1. Add support pon act led and maple reset to asxvolt16
2. Modify tx_dsable port mapping
=> Add support pon act led and maple reset to asxvolt16

README.md
removed one space, so one can see if build is passing or not :)
=> fixed build status badge

packages/platforms/ingrasys/x86-64/s9180-32x/onlp/builds/x86_64_ingrasys_s9180_32x/module/src/sysi.c, packages/platforms/ingrasys/x86-64/s9180-32x/onlp/builds/x86_64_ingrasys_s9180_32x/module/src/x86_64_ingrasys_s9180_32x_module.c, packages/platforms/ingrasys/x86-64/s9230-64x/onlp/builds/x86_64_ingrasys_s9230_64x/module/src/x86_64_ingrasys_s9230_64x_module.c, packages/platforms/ingrasys/x86-64/s9280-64x/onlp/builds/x86_64_ingrasys_s9280_64x/module/src/x86_64_ingrasys_s9280_64x_module.c
[ingrasys] fix typo for ingrasys platform
=> [ingrasys] fix typo for ingrasys platform

packages/platforms/accton/x86-64/as5912-54x/onlp/builds/x86_64_accton_as5912_54x/module/src/fani.c, packages/platforms/accton/x86-64/as5912-54x/onlp/builds/x86_64_accton_as5912_54x/module/src/platform_lib.c, packages/platforms/accton/x86-64/as5912-54x/onlp/builds/x86_64_accton_as5912_54x/module/src/platform_lib.h, packages/platforms/accton/x86-64/as5912-54x/onlp/builds/x86_64_accton_as5912_54x/module/src/psui.c
=> [as5912_54x]:Support DC PSU onlp

packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/fani.c
Reviewer: @jnealtowns @zhouzi88
=> SWL-5901 as7326 fan register value for f2b should be 0

packages/platforms/accton/x86-64/as7312-54x/onlp/builds/x86_64_accton_as7312_54x/module/src/platform_lib.c, packages/platforms/accton/x86-64/as7312-54xs/onlp/builds/x86_64_accton_as7312_54xs/module/src/platform_lib.c
Reviewer: @jnealtowns @zhouzi88
=> SWL-5903 minor fix on as7312-54x/xs

packages/platforms/accton/x86-64/asgvolt64/modules/builds/x86-64-accton-asgvolt64-cpld.c
=> [asgvolt64]:support lp mode sysfs

packages/platforms/accton/x86-64/as9716_32d/modules/builds/x86-64-accton-as9716-32d-cpld.c, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/sfpi.c
Add to support QSFP-DD reset sysfs.
=> [as9716-32d]:Add to support qsfp-dd reset sysfs

packages/platforms/accton/x86-64/asgvolt64/modules/builds/x86-64-accton-asgvolt64-fpga.c, packages/platforms/accton/x86-64/asgvolt64/platform-config/r0/src/python/x86_64_accton_asgvolt64_r0/__init__.py
[ASGVOLT64]Implement FPGA driver
=> [ASGVOLT64]Implement FPGA driver

packages/platforms/accton/x86-64/as7926-40xke/modules/builds/x86-64-accton-as7926-40xke-cpld.c, packages/platforms/accton/x86-64/as7926-40xke/onlp/builds/x86_64_accton_as7926_40xke/module/src/sfpi.c, packages/platforms/accton/x86-64/as9716_32d/modules/builds/x86-64-accton-as9716-32d-cpld.c, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/sfpi.c
=> [AS7926_40xke]Support qsfp  reset sysfs

packages/platforms/accton/x86-64/as9716_32d/modules/builds/x86-64-accton-as9716-32d-psu.c, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/platform_lib.c, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/platform_lib.h, packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/psui.c
Serial number of new psu is changed from 0x2e to 0x35.
So modify code to support it.  Besides, the DUT support two psu.
SN length is different.
=> [as9716-32d]Modify to read psu SN offset

packages/platforms/accton/x86-64/as7926-40xke/onlp/builds/x86_64_accton_as7926_40xke/module/src/sfpi.c
Fix port_reset use addr, bus error for from port 42 to 54.
=> [as7926_40xke]Fix port_reset use addr, bus error

packages/platforms/accton/x86-64/as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-sys.c, packages/platforms/accton/x86-64/as5916-54xl/modules/builds/x86-64-accton-as5916-54xl-sys.c
The command to reset mac are as follows:
=> [as5916-54xks/xl] Add sysfs to support mac reset

packages/platforms/accton/x86-64/as7315-27xb/onlp/builds/x86_64_accton_as7315_27xb/module/src/sysi.c
Signed-off-by: roy_lee <roy_lee@accton.com>
Update the fan control, add 1 more stage for duty 60%.
It will have 4 stages of duties, 10%, 30%, 60% and 100%.
=>  [platform/accton] as7315-27xb: update for new fan control plan.

packages/platforms/accton/x86-64/as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-sys.c, packages/platforms/accton/x86-64/as5916-54xl/modules/builds/x86-64-accton-as5916-54xl-sys.c
Signed-off-by: WillyLiu-EC <willy_liu@edge-core.com>
=> [as5916-54xl/as5916-54xks] add sysfs of bios flash id and modify sysfs of mac reset

packages/platforms/accton/x86-64/as5835-54x/platform-config/r0/src/python/x86_64_accton_as5835_54x_r0/__init__.py
Signed-off-by: Jostar Yang <jostar_yang@accton.com.tw>
=> [as5835-54x]Set tx_dis to disable when each boot

packages/platforms/accton/x86-64/as5916-54xks/onlp/builds/x86_64_accton_as5916_54xks/module/src/sfpi.c, packages/platforms/accton/x86-64/as5916-54xl/onlp/builds/x86_64_accton_as5916_54xl/module/src/sfpi.c, packages/platforms/accton/x86-64/as7316-26xb/modules/builds/x86-64-accton-as7316-26xb-sfp.c, packages/platforms/accton/x86-64/as7316-26xb/onlp/builds/x86_64_accton_as7316_26xb/module/src/sfpi.c
Signed-off-by: brandon_chuang <brandon_chuang@edge-core.com>
=> [as5916-54/as7316-26xb] Support onlp_sfpi_dev_read/write functions

packages/base/any/kernels/modules/ym2651y.c, packages/platforms/accton/x86-64/as7712-32x/onlp/builds/x86_64_accton_as7712_32x/module/src/fani.c, packages/platforms/accton/x86-64/as7712-32x/onlp/builds/x86_64_accton_as7712_32x/module/src/platform_lib.c, packages/platforms/accton/x86-64/as7712-32x/onlp/builds/x86_64_accton_as7712_32x/module/src/platform_lib.h, packages/platforms/accton/x86-64/as7712-32x/onlp/builds/x86_64_accton_as7712_32x/module/src/psui.c, packages/platforms/accton/x86-64/as7712-32x/onlp/builds/x86_64_accton_as7712_32x/module/src/thermali.c
Signed-off-by: brandon_chuang <brandon_chuang@edge-core.com>
=> [as7712-32x] Set the thermal threshold of each PSU model

packages/platforms/accton/x86-64/as4630-54pe/modules/builds/x86-64-accton-as4630-54pe-psu.c, packages/platforms/accton/x86-64/as4630-54pe/onlp/builds/x86_64_accton_as4630_54pe/module/src/platform_lib.c
Signed-off-by: Jostar Yang <jostar_yang@accton.com>
=> [as4630-54pe]Modify to read psu ID and SN

packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/sysi.c
Signed-off-by: Jostar Yang <jostar_yang@accton.com>
=> [as7326_56x]Fix thermal fan when fan insert back

packages/platforms/accton/x86-64/as4630-54pe/onlp/builds/x86_64_accton_as4630_54pe/module/src/sysi.c, packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/sysi.c, packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/sysi.c
Signed-off-by: Jostar Yang <jostar_yang@accton.com.tw>
=> [as7726-32x] Fix use '%' in AIM_LOG string

packages/platforms/alphanetworks/x86-64/stx60d0-126f/onlp/builds/x86_64_alphanetworks_stx60d0_126f/module/src/fani.c, packages/platforms/alphanetworks/x86-64/stx60d0-126f/onlp/builds/x86_64_alphanetworks_stx60d0_126f/module/src/platform_lib.c, packages/platforms/alphanetworks/x86-64/stx60d0-126f/onlp/builds/x86_64_alphanetworks_stx60d0_126f/module/src/platform_lib.h, packages/platforms/alphanetworks/x86-64/stx60d0-126f/onlp/builds/x86_64_alphanetworks_stx60d0_126f/module/src/psui.c
1. Front panel PSU-1/PSU-2 exchanged.
original: front left to right are PSU-2, PSU-1
new: front left to right are PSU-1, PSU-2
2. Rear panel fan1-4 sort exchanged.
original: front left to right are FAN4, FAN3, FAN2, FAN1
new: front left to right are FAN1, FAN2, FAN3, FAN4
=> [stx60d0-126f]Beta build HW modify, front panel PSU-1/PSU-2 exchanged and rear panel FAN 1-4 sort exchanged.

packages/platforms/accton/x86-64/as5835-54t/onlp/builds/x86_64_accton_as5835_54t/module/src/fani.c, packages/platforms/accton/x86-64/as5835-54t/onlp/builds/x86_64_accton_as5835_54t/module/src/platform_lib.c, packages/platforms/accton/x86-64/as5835-54t/onlp/builds/x86_64_accton_as5835_54t/module/src/platform_lib.h, packages/platforms/accton/x86-64/as5835-54t/onlp/builds/x86_64_accton_as5835_54t/module/src/psui.c
New PSU: YM-2401HCR, YM-2401HDR
Signed-off-by: Sean Wu <sean_wu@edge-core.com>
=> [as5835-54t] support new DC PSU

packages/base/any/kernels/modules/ym2651y.c, packages/platforms/accton/armxx/arm-accton-as4610/arm_accton_as4610/module/src/platform_lib.c, packages/platforms/accton/armxx/arm-accton-as4610/arm_accton_as4610/module/src/platform_lib.h, packages/platforms/accton/armxx/arm-accton-as4610/arm_accton_as4610/module/src/psui.c, packages/platforms/accton/armxx/arm-accton-as4610/modules/accton_as4610_psu.c
psu @ 1 = {
Description: PSU-1
Model:  YM-1601A
SN:     SA000P121518000062
Status: 0x00000001 [ PRESENT ]
Caps:   0x00000151 [ AC,VOUT,IOUT,POUT ]
Vin:    0
Vout:   54750
Iin:    0
Iout:   472
Pin:    0
Pout:   26000
}
psu @ 2 = {
Description: PSU-2
Model:  DPS-920AB B
SN:     JQDD2125001617
Status: 0x00000001 [ PRESENT ]
Caps:   0x00000151 [ AC,VOUT,IOUT,POUT ]
Vin:    0
Vout:   54613
Iin:    0
Iout:   367
Pin:    0
Pout:   20000
}
=> [as4610] Support Delta PSU DPS-920AB

packages/platforms/accton/x86-64/as7316-26xb/modules/builds/x86-64-accton-as7316-26xb-sys.c, packages/platforms/accton/x86-64/as7316-26xb/onlp/builds/x86_64_accton_as7316_26xb/module/src/sysi.c
[Edgecore][AS7316_26XB] Add cpld and fpga version sysfs and onlpdump -x support
1. Add sysfs for mainboard, cpu board, fan board cpld, and fpga versions.
2. Add support of onlpdump -x, which prints out cpld and fpga versions.
3. Modified the layout of x86-64-accton-as7316-26xb-sys.c to linux coding style
=> [Edgecore][AS7316_26XB] Add cpld and fpga version sysfs and onlpdump -x support

packages/platforms/accton/x86-64/as9716_32d/platform-config/r0/src/python/x86_64_accton_as9716_32d_r0/__init__.py
Config TI retimer chip for SFP to make the traffic work.
=> [Edgecore][as9716-32d] Config TI retimer for SFP

packages/platforms/accton/x86-64/as7726-32x/modules/builds/x86-64-accton-as7726-32x-fan.c, packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/fani.c, packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/platform_lib.h, packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/sysi.c
We enable fan-watchdog to enhance fan controller.
=> [Edgecore][AS7726-32X] Enhance fan controller to execute fan-watchdog

packages/base/any/kernels/modules/ym2651y.c, packages/platforms/accton/x86-64/as7726-32x/modules/builds/x86-64-accton-as7726-32x-psu.c, packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/platform_lib.c, packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/psui.c
Modify PSU related files to support new PSU model: FSF045-611G
Signed-off-by: brandonchuang <brandon_chuang@edge-core.com>
=> [Edgecore][as7726-32x] Support Acbel PSU FSF045-611G

packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/sfpi.c
We add function to control QSFP Tx disable
=> [Edgecore][AS7326-56X] Add controlling function of QSFP Tx disable

packages/base/any/kernels/modules/ym2651y.c, packages/platforms/accton/x86-64/as7326-56x/modules/builds/x86-64-accton-as7326-56x-psu.c, packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/platform_lib.c, packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/psui.c
We add driver and related code to support Acbel PSU FSF045-611G.
Signed-off-by: Willy Liu <willy_liu@edge-core.com>
=> [Edgecore][as7326-56x] Support Acbel PSU FSF045-611G

packages/platforms/accton/x86-64/as7326-56x/modules/builds/x86-64-accton-as7326-56x-leds.c
1. We fixed the issue that getting loc wrong value
2. We fixed the issue that blinking failed led type.
Signed-off-by: Willy Liu <willy_liu@edge-core.com>
=> [Edgecore][as7326-56x] Fix LED issues

packages/base/any/kernels/modules/optoe.c
The optoe first creates the sysfs entries and then calls i2c_set_clientdata(), but a very fast userspace may already try to access the sysfs entries before the clientdata was set. This then leads to a NULL pointer access, crashing the kernel.
Fix this by ensuring the sysfs entries are only registered after clientdata is populated.
Fixes the following crash observed on boot:
```
Sep 28 18:59:33 accton-as4630-54pe kernel: i2c i2c-18: new_device: Instantiated device optoe2 at 0x50 Sep 28 18:59:33 accton-as4630-54pe kernel: BUG: kernel NULL pointer dereference, address: 0000000000000048 Sep 28 18:59:33 accton-as4630-54pe kernel: optoe 18-0050: 33152 byte optoe2 EEPROM, read/write Sep 28 18:59:33 accton-as4630-54pe kernel: #PF: supervisor write access in kernel mode Sep 28 18:59:33 …
```
=> optoe: fix race in sysfs registration on probe

packages/platforms/accton/x86-64/as5916-54xks/onlp/builds/x86_64_accton_as5916_54xks/module/src/sfpi.c
1. Support QSFP reset funcion
2. Support QSFP LP mode
=> [Edgecore][AS5916-54XKS] Support QSFP reset funcion and LP mode

packages/platforms/accton/x86-64/as7535-28xb/onlp/builds/x86_64_accton_as7535_28xb/module/src/sfpi.c
Enhanced sfpi.c for AS7535-28XB-O-AC-F to support ONLP_SFP_CONTROL for 'Soft Rate_Select Select' 
Added read/write API's for Multirate soft select in sfp control get/set, for multirate supporting tranceivers
Ref : SFF-8472 Specification for Management Interface for SFP+
Note :ONL Code got approved and merged into the master (Ref : #984)
Test System :
Platform : AS7535-28XB-O-AC-F
Transceiver used for testing : FiniserFTLX8574D3BCV, it supports multimode rates (1G/10G). https://www.epsglobal.com/Media-Library/EPSGlobal/Products/files/finisar/transceivers/FTLX8574D3BCV.pdf?ext=.pdf
The port with the above transceiver is connected to IXIA port with same transceiver
Scenario tested :
Port UP & DOWN state changes are verified
Also modified port rate between 1G and 10G
Validated the values of …
=>  Enhanced sfpi.c for AS7535-28XB-O-AC-F to support ONLP_SFP_CONTROL for 'Soft Rate_Select Select' 
