opencomputeproject/OpenNetworkLinux

- packages/base/any/onlp/src/onlp/module/src/platform_manager.c
Originally from @zhouzi88 https://github.com/opennetworklinux/ONLP/pull/21 , factored into OpenNetworkLinux
> report initial fan/psu failed state to syslog pull 21 from onlp

- Makefile
@jnealtowns 
I ended up typing the ./docker/tools/onlbuilder blah blah so many times that I added this to save sanity.  The double ifndef() line in the Makefile isn't great, but let me know if you care or want something nicer.
> added `make docker-debug` target

- docker/tools/docker_shell
This change checks if qemu-ppc exists, if not, checks if the binfmt_misc file system is mounted, if not, mounts it and starts the binfmt-support script.
> Updates to docker_shell to setup binfmt

- packages/platforms/accton/x86-64/x86-64-accton-as7512-32x/platform-config/r0/src/python/x86_64_accton_as7512_32x_r0/__init__.py
Dumb error, causes python-minimal and 28 other packages to not get installed properly. Confirmed good on as5712
previous:
root@localhost:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
28 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] n
post change:
root@localhost:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
issue:
Setting up python2.7-minimal (2.7.9-2) ...
Linking and byte-compiling packages for runtime python2.7...
Sorry: IndentationError: unexpected indent …
> removed extra brackets from __init__.py for AS7512

- Makefile
- packages/base/amd64/initrds/Makefile
There are some subtle corners on the onlpm dependency processing which need to be addressed. 
Until then, the build steps in the top-level makefile have been broken into the correct sequence.
> Explicit Build Dependencies

- docker/tools/onlbuilder
Previously only $HOME was mounted in developer mode.
Now $HOME and $CWD are both mounted for convenience.
This can be disabled using the --no-mount-current option.
> Mount the current working directory in addition to $HOME by default.

- setup.env
Built without issue.
INFO:onlpm:Releasing ONL-2.0.0_ONL-OS_2016-04-19.1838-6c47197_PPC_INSTALLER -> OpenNetworkLinux.br/RELEASE/wheezy/powerpc/
> moved default buildroot mirror from github to opencompute server

- docs/BootProcess.md
- docs/GettingStarted.md
- docs/PersistWorkflow.md
- docs/PortingGuide.md
- packages/base/all/vendor-config-onl/src/python/onl/install/App.py
- packages/base/all/vendor-config-onl/src/python/onl/platform/current.py
reviewers @jnealtowns @carlroth trivial change to installer python files to handle Mellanox use of . in their ONIE identifier.  Also some updates to the documentation.
> allows for the use of . in onie identifiers and updates documentation

- packages/platforms/accton/x86-64/x86-64-accton-wedge-16x/platform-config/r0/src/lib/x86-64-accton-wedge-16x-r0.yml
- packages/platforms/accton/x86-64/x86-64-facebook-wedge100/platform-config/r0/src/lib/x86-64-facebook-wedge100-r0.yml
@capveg @jnealtowns only one switch (AS5512) left on the 3.18 kernel.
> Updates the Wedge 40 and 100 systems to use the 3.16 kernel

- packages/base/all/vendor-config-onl/src/python/onl/install/BaseInstall.py
- handle more pyparted exceptions
- properly clobber the disk signature
I did some ad-hoc testing on this on a ppc machine:
1. properly handles valid msdos disk label
2. properly handles valid gpt disk label (reformats to msdos)
3. properly handles "empty" (dd if=/dev/null) disk label
> Handle unformatted/corrupted partition tables, see SWL-3246

- packages/base/any/faultd/APKG.yml
This change allows base-files to be installed and set up before faultd.
> adds base-files dependency to faultd

- packages/base/all/vendor-config-onl/src/python/onl/install/BaseInstall.py
- packages/base/all/vendor-config-onl/src/python/onl/install/plugins/__init__.py
- drop plugin files into $pydir/onl/install/plugins
- embed plugins into the loader initrd and decouple from the installer
> Import plugins from the loader runtime

- packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_sensors.c
If sensor is not present, return a value of zero or a zero-length string.
Sample output from onl-snmpwalk:
```
OCP-ONL-SENSOR-MIB::onlPSUSensorsIndex.1 = INTEGER: 1
OCP-ONL-SENSOR-MIB::onlPSUSensorsIndex.2 = INTEGER: 2
OCP-ONL-SENSOR-MIB::onlPSUSensorsDevice.1 = STRING: PSU 1 - PSU-1
OCP-ONL-SENSOR-MIB::onlPSUSensorsDevice.2 = STRING: PSU 2 - PSU-2
OCP-ONL-SENSOR-MIB::onlPSUSensorsStatus.1 = INTEGER: 2
OCP-ONL-SENSOR-MIB::onlPSUSensorsStatus.2 = INTEGER: 1
OCP-ONL-SENSOR-MIB::onlPSUSensorsCurrentType.1 = STRING: unknown
OCP-ONL-SENSOR-MIB::onlPSUSensorsCurrentType.2 = STRING: ac
OCP-ONL-SENSOR-MIB::onlPSUSensorsModel.1 = STRING: 
OCP-ONL-SENSOR-MIB::onlPSUSensorsModel.2 = STRING: CPR-4011-4M11
OCP-ONL-SENSOR-MIB::onlPSUSensorsVin.1 = Gauge32: 0 …
```
> Always call snmp_set_var_typed_value so that snmpwalk does not prematurely terminate

- packages/base/any/onlp-snmpd/builds/src/onlp_snmp/module/src/onlp_snmp_platform.c
In resource_int_register, use netsnmp_register_instance so that SNMP trap can be generated.
> onlp-snmp: registering onl resource

- packages/base/any/onlp/src/onlp/module/src/thermal.c
Apparently the period at the end of "State: Missing." results in a malformed enumeration value.
> If the thermal sensor is missing, call onlp_oid_show_state_missing().

- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/fani.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/ledi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/sfpi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2100/onlp/builds/src/module/src/sysi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/fani.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/ledi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/sfpi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2410/onlp/builds/src/module/src/sysi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/fani.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/ledi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/sfpi.c
- packages/platforms/mellanox/x86-64/x86-64-mlnx-msn2700/onlp/builds/src/module/src/sysi.c
Added onlp_sfp_dev_readb and onlp_sfp_dev_readw support to msn2100, msn2410 and msn2700 systems
Signed-off-by: Oleksandr Shamray <oleksandrs@mellanox.com>
> Add onlp_sfp_dev_readb and onlp_sfp_dev_readw support

- packages/base/any/kernels/4.9-lts/configs/x86_64-all/x86_64-all.config
- packages/base/any/kernels/4.9-lts/patches/driver-support-intel-igb-bcm5461-phy.patch
- packages/base/any/kernels/4.9-lts/patches/series
Patch provided by David Ahern @dsahern for kernel 4.11 based on 3.16-lts ONL patch.  Verified working on kernel 4.9.30.
> igb: Add support for bcm5461x phy

- packages/platforms/accton/x86-64/x86-64-accton-as7312-54x/platform-config/r0/src/python/x86_64_accton_as7312_54x_r0/__init__.py
With wrong PSU drivers, ONLP cannot get the correct status of power modules.
> [Platform]Accton as7312_54x, fixes insertion of the wrong psu driver

- builds/any/installer/installer.sh.in
- packages/base/all/vendor-config-onl/src/lib/install/lib.sh
- try to find the boot device
- try to determine if the boot device is GPT
- use sgdisk to correct simple errors
- tested on EFI and non-EFI systems, not yet tested on ppc
> Proactively fix GPT partition tables, see SWL-3971

- .gitmodules
- packages/platforms/delta/x86-64/x86-64-delta-ag5648/.gitignore
- packages/platforms/quanta/x86-64/x86-64-quanta-ly4r/.gitignore
- setup.env
A new build-artifacts repository has been introduced to provide prebuilt binaries for ONL packages which change so infrequently that they should never really need to be rebuilt. 
These artifacts are part of a different repository so they can be managed separately from (and not bloat permanently and unnecessarily) the main ONL repository. 
The first artifacts added here are for the buildroot cpio packages. These will be pre populated at setup time into the local REPO. 
This prebuilt artifact does not preclude rebuilding the package locally if necessary.
> Support Prebuilt Artifacts

- builds/any/installer/installer.sh.in
- packages/base/all/vendor-config-onl/src/bin/onie-sysinfo
- packages/base/all/vendor-config-onl/src/lib/install/lib.sh
- packages/base/all/vendor-config-onl/src/python/onl/install/App.py
- packages/base/all/vendor-config-onl/src/python/onl/install/ShellApp.py
- packages/base/all/vendor-config-onl/src/python/onl/install/SystemInstall.py
- packages/base/all/vendor-config-onl/src/python/onl/platform/current.py
- packages/base/all/vendor-config-onl/src/python/onl/upgrade/loader.py
- packages/platforms/mellanox/vendor-config/src/python/mellanox/__init__.py
- use onie-shell (chroot into ONIE initrd) to access onie-sysinfo bits
- machine.conf support lingers a bit for older images
Tested on x86 (GRUB) and PPC
> Use onie-sysinfo instead of machine.conf, see SWL-4279

- packages/platforms/quanta/x86-64/modules/builds/optoe.c
- packages/platforms/quanta/x86-64/x86-64-quanta-ly8-rangeley/modules/builds/quanta_platform_ly8.c
- packages/platforms/quanta/x86-64/x86-64-quanta-ly8-rangeley/onlp/builds/src/x86_64_quanta_ly8_rangeley/module/src/sfpi.c
- packages/platforms/quanta/x86-64/x86-64-quanta-ly8-rangeley/platform-config/r0/src/python/x86_64_quanta_ly8_rangeley_r0/__init__.py
1. Migrate device driver from opencomputeproject/oom/optoe
2. Change device driver of eeprom from 24c02 to optoe
3. Use platform data to initial port_name
4. BITMAP is set by port_name
> [Quanta-LY8] Add Support for OOM:

- builds/any/rootfs/jessie/standard/standard.yml
- builds/any/rootfs/stretch/standard/standard.yml
- builds/any/rootfs/wheezy/standard/standard.yml
- docs/README-proxy.md
Let me know if your open to changing the default git repo URLs to use https:// instead of git:// which would remove a step.  At least https://help.github.com/articles/which-remote-url-should-i-use/ seems to recommend it as a default but I'm not sure of all of the implications.
> Added doc and support for building behind an HTTP proxy

- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/Makefile
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/modules/Makefile
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/modules/PKG.yml
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/onlp/Makefile
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/onlp/PKG.yml
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/platform-config/Makefile
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/platform-config/r0/Makefile
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/platform-config/r0/PKG.yml
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/platform-config/r0/src/lib/x86-64-accton-wedge100s-32x-r0.yml
- packages/platforms/accton/x86-64/x86-64-accton-wedge100s-32x/platform-config/r0/src/python/x86_64_accton_wedge100s_32x_r0/__init__.py
Basic support for the Wedge 100S using the 4.9 kernel.
> Adding support for Wedge 100S

- packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/modules/builds/x86-64-accton-as5712-54x-cpld.c
- packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/modules/builds/x86-64-accton-as5712-54x-fan.c
- packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/modules/builds/x86-64-accton-as5712-54x-leds.c
- packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/modules/builds/x86-64-accton-as5712-54x-psu.c
- packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/modules/builds/x86-64-accton-as5712-54x-sfp.c
- packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/onlp/builds/src/module/src/sfpi.c
- packages/platforms/accton/x86-64/x86-64-accton-as5712-54x/platform-config/r0/src/python/x86_64_accton_as5712_54x_r0/__init__.py
Reverts opencomputeproject/OpenNetworkLinux#294
@brandonchuang These changes must be reverted as they are currently breaking the proper reading and identification of some fiber modules.
> Revert "[as5712-54x] Add support for OOM driver"

- packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-cpld.c
- packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-fan.c
- packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-leds.c
- packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-psu.c
- packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/modules/builds/x86-64-accton-as5812-54x-sfp.c
- packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/onlp/builds/src/module/src/sfpi.c
- packages/platforms/accton/x86-64/x86-64-accton-as5812-54x/platform-config/r0/src/python/x86_64_accton_as5812_54x_r0/__init__.py
Reverts opencomputeproject/OpenNetworkLinux#340
@brandonchuang These changes must be reverted as they are currently breaking the proper reading and identification of some fiber modules.
> Revert "[as5812-54x] Add support for OOM"

- packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/modules/builds/x86-64-accton-as6812-32x-cpld.c
- packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/modules/builds/x86-64-accton-as6812-32x-fan.c
- packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/modules/builds/x86-64-accton-as6812-32x-leds.c
- packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/modules/builds/x86-64-accton-as6812-32x-psu.c
- packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/modules/builds/x86-64-accton-as6812-32x-sfp.c
- packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/onlp/builds/src/module/src/sfpi.c
- packages/platforms/accton/x86-64/x86-64-accton-as6812-32x/platform-config/r0/src/python/x86_64_accton_as6812_32x_r0/__init__.py
Reverts opencomputeproject/OpenNetworkLinux#339
@brandonchuang These changes must be reverted as they are currently breaking the proper reading and identification of some fiber modules.
> Revert "[as6812-32x] Add support for OOM"

- packages/platforms/accton/x86-64/x86-64-accton-as7326-56x/onlp/builds/src/module/src/platform_lib.c
- packages/platforms/accton/x86-64/x86-64-accton-as7326-56x/platform-config/r0/src/python/x86_64_accton_as7326_56x_r0/__init__.py
By the comment of https://github.com/opencomputeproject/OpenNetworkLinux/pull/347,
commit for
1. correct SYS_OBJECT_ID.
2. replace local file write API to one in onlplib.
Signed-off-by: roy_lee <roy_lee@accton.com>
> [Accton as7326_56x] Fixed upon comment of PR 347

- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/sfpi.c
Fixed bug of showing shifted SFP EEPROM data, by shifting value by 2 bytes.
> Fixed bug of showing shifted SFP EEPROM data

- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/ledi.c
Changed the RED LED register value to Blue and changed the BLUE LED register value to Red.
Tested successfully and result is System LED1 and LED2 can blink and turn ON respectively with correct color using onlp_led_mode_set function.
> Fixed SYSTEM LED RED and BLUE reversed wrong color issue

- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/sfpi.c
Replaced data[i] and data[i+1] with data[i2] and data[(i2)+1] respectively in sfpi.c file. After replacing, connected the innolight transceiver to Accton Wedge100BF_65x SFP port to read the SFP EEPROM and data can be read correctly.
> Fixed onlp_sfp_eeprom_read shifts QSFP EEPROM data

- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/ledi.c
Interchanged the color codes of System LED1 and System LED2 for Blue and Red color for Wedge100 Barefoot 65x.
> fixing the issue of wrong color of system LEDs

- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/onlp/builds/src/module/src/sysi.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/platform-config/r0/src/python/x86_64_accton_as5916_54xks_r0/__init__.py
Modify sysi to read eeprom via word_data due to use block mode will get error for some eeprom.
> Modify sysi to read eeprom via word_data.

- packages/base/any/kernels/modules/optoe.c
Correct a panic inducing defect which is triggered on a read (or write)
which begins beyond byte 128, on a byte which is not aligned on a 128 byte
chunk boundary, and which crosses a chunk boundary.
> [oom] Correct a panic inducing defect which is triggered on a read (or write)

- builds/any/rootfs/jessie/common/all-base-packages.yml
- builds/any/rootfs/stretch/common/all-base-packages.yml
- builds/any/rootfs/wheezy/common/all-base-packages.yml
- packages/base/all/initrds/loader-initrd-files/src/bin/ifup
- packages/base/all/vendor-config-onl/src/python/onl/bootconfig/__init__.py
With this series I present following fixes and improvements to base ONL system:
1) Make ifup from initrds to skip when NETAUTO="none"  to support Debian networking configuration.
2) Make NETRETRIES checks private to NETAUTO="dhcp" mode in ifup from initrds.
3) Explicitly add debconf and dialog to base packages on all arches: debconf.
See individual commit description messages for more details on proposed changes.
> Assorted set of fixes and improvements to ONL

- packages/platforms/accton/x86-64/x86-64-accton-as7716-32x/onlp/builds/src/module/src/sysi.c
- packages/platforms/accton/x86-64/x86-64-accton-as7716-32x/platform-config/r0/src/python/x86_64_accton_as7716_32x_r0/__init__.py
Use i2c word mode instead of use block mode for access sys eeprom
> Use i2c word mode instead of use block mode for access sys eeprom

- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xm/onlp/builds/src/module/src/thermali.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xm/platform-config/r0/src/python/x86_64_accton_as5916_54xm_r0/__init__.py
For R0B board or later version, hardware has changed a LM75 sensor from from 0x48 to 0x4C.
Due to this change, ONLP has to be updated to tell if running on R0A or other version of PCB.
Onlpdump will examine device on 0x4C of i2c bus 10 to judge whether it's later version of underlying hardware.
> [as5916_54xm]Change one thermal sensor's i2c address to be 0x4C or 0x48.

- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/platform_lib.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/psui.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/sfpi.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/sysi.c
1. old method: open UART and close UART whenever we need to get information from BMC.
new method: open UART at beginning, then we use the UART(TTY) device directly.
2. old method: use onlp_i2c_readw() to get all QSFP/SFP's eeprom data, it spends 128 times i2c access time.
new method: use OOM's sysfs
3. reduce the UART(TTY) retry time and timeout time
4. add PSU's serial number information
(sysi.c: only add one line "bmc_tty_init();", the others are related to ^M)
> enhance get data performance

- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/platform_lib.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/psui.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/sfpi.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/sysi.c
1. old method: open UART and close UART whenever we need to get information from BMC.
new method: open UART at beginning, then we use the UART(TTY) device directly.
2. old method: use onlp_i2c_readw() to get all QSFP/SFP's eeprom data, it spends 128 times i2c access time.
new method: use OOM's sysfs
we also correct the port mapping
3. reduce the UART(TTY) retry time and timeout time
4. add PSU's serial number information
(sysi.c: only add one line "bmc_tty_init();", the others are related to ^M)
> [wedge100bf-65x] enhance get data performance

- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-fan.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-leds.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-psu.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-sfp.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-sys.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-thermal.c
1. Add the CPLD watchdog function
2. Enhance the mutex lock protection of peripheral drivers.
> [as5916-54xks] Add cpld watchdog / enhance mutex protection of peripheral drivers

- packages/platforms/accton/x86-64/x86-64-accton-as5916-26xb/modules/builds/x86-64-accton-as5916-26xb-psu.c
- packages/platforms/accton/x86-64/x86-64-accton-as5916-26xb/onlp/builds/src/module/src/psui.c
- packages/platforms/accton/x86-64/x86-64-accton-as7316-26xb/modules/builds/x86-64-accton-as7316-26xb-psu.c
- packages/platforms/accton/x86-64/x86-64-accton-as7316-26xb/onlp/builds/src/module/src/psui.c
Fix wrong fan speed of DC PSU at AS5916-26xb and AS7316-26xb. 
Targeted for a DC-to-DC PSU, named YM-2401U,
Code change for: 
1. For x86-64-accton-as5916-26xb-psu.c/x86-64-accton-as7316-26xb-psu.c, take 2 bytes RPM as unsigned bytes. Do this to avoid sign extension.
2. For psui.c of onlpdump, examine model name to tell if a PSU is DC-DC or AC-DC, and set the capability accordingly.
> [platform]as5916-26xb/as7316-26xb: add support for DC-PSU, model YM-2401U.

- packages/base/any/kernels/4.9-lts/patches/0014-platform-x86-mlx-platform-backport-from-4.19.patch
- packages/base/any/kernels/4.9-lts/patches/0015-platform-x86-mlx-platform-Add-support-for-register-a.patch
- packages/base/any/kernels/4.9-lts/patches/series
This patch combines backporting of upstream code from the kernel 4.19 
Author: Oleksandr Shamray <oleksandrs@mellanox.com>
platform/x86: mlx-platform: Add support for register CPLD3_VER, RST_CUSE
Add NG system type support
Author: Vadim Pasternak <vadimp@mellanox.com>
platform/x86: mlx-platform: backport from 4.19
> Added kernel 4.9 patches for mlx-platform

- builds/any/installer/grub/builds/Makefile
- builds/any/installer/uboot/builds/Makefile
- tools/mkinstaller.py
- tools/onl-nos-create.py
To show ONL version at image installation time add --onl-version
option to mkinstaller.py and pass VERSION_STRING to it.
Fixes: 9a98e40c09c7 ("Use the new mkinstaller script.")
Signed-off-by: Sergey Popovich <sergey.popovich@ordnance.co>
> mkinstaller.py: Substitude ONLVERSION in installer.sh.in template

- packages/base/all/initrds/loader-initrd-files/src/bin/initrng.py
- packages/base/all/initrds/loader-initrd-files/src/bin/sysinit
We start using Linux RNG from initrd with low entropy pools and random
data quality might not be good. Kernel warns us about the problem with
following messages in dmesg(1):
[    4.786307] random: onl-mounts: uninitialized urandom read (16 bytes read, 46 bits of entropy available)
[    5.307536] random: onl-mounts: uninitialized urandom read (16 bytes read, 83 bits of entropy available)
[    5.354480] random: blkid: uninitialized urandom read (6 bytes read, 89 bits of entropy available)
[    5.366963] random: blkid: uninitialized urandom read (6 bytes read, 90 bits of entropy available)
[    5.379385] random: blkid: uninitialized urandom read (6 bytes read, 90 bits of entropy available)
[    5.391910] random: blkid: uninitialized urandom read (6 bytes read, 90 bits of entropy available)
[ …
> ordnance: Initialize Linux Random Number Generator (RNG) early

- packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/fani.c
- packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/platform_lib.c
- packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/psui.c
- packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/onlp/builds/src/module/src/sfpi.c
- packages/platforms/delta/x86-64/x86-64-delta-agc7648sv1/platform-config/r0/src/python/x86_64_delta_agc7648sv1_r0/__init__.py
The gpio_pca953x driver export gpio value for fan present bit.
However, it will lead to GPIO driver init fail by CPU and BMC access buses at the same time while system is bring up.
In order to prevent bus conflict, to disable BMC Monitor function before kernel drivers initialization.
> Disable BMC Monitor before bus init to prevent conflict with BMC.

- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/platform_lib.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/psui.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/platform_lib.c
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/platform_lib.h
- packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-65x/onlp/builds/src/module/src/psui.c
old method: use i2c raw command to access PSU
new method: use OpenBMC's sysfs to access PSU
> we change the method to get PSU's EEPROM data.

- packages/base/any/kernels/4.14-lts/patches/0003-drivers-net-ethernet-broadcom-tg3.patch
- packages/base/any/kernels/4.14-lts/patches/series
This is for the patch the Broadcom tg3 driver to support 100M/10M Ethernet port.
The patch has been verified in platform_accton_asxvolt16. Note that the patch didn't include CONFIG_TIGON3_PHY_SERDES which is not used for accton_asxvolt16.
> Add broadcom tg3 support 100M/10M feature.

- packages/platforms/accton/x86-64/x86-64-accton-as5916-54xk/platform-config/r1/src/python/x86_64_accton_as5916_54xk_r1/__init__.py
- packages/platforms/accton/x86-64/x86-64-accton-as9716_32d/platform-config/r0/src/python/x86_64_accton_as9716_32d_r0/__init__.py
- packages/platforms/accton/x86-64/x86-64-accton-asgvolt64/platform-config/r0/src/python/x86_64_accton_asgvolt64_r0/__init__.py
IR3570A chip cause problem when read eeprom by i2c-block mode.
It happen when read 16th-byte offset that value is 0x8. So disable chip when find it.
> Fix IR3570A issue that cause read eeprom problem

- packages/base/any/kernels/4.9-lts/patches/0031-mlxsw-core-Skip-port-split-entries-in-hwmon-subsyste.patch
- packages/base/any/kernels/4.9-lts/patches/0032-mellanox-platform-Backporting-Melanox-drivers-from-v.patch
- packages/base/any/kernels/4.9-lts/patches/series
Added Mellanox kernel drier patches 
0031-mlxsw-core-Skip-port-split-entries-in-hwmon-subsyste.patch:
1. Skip split entries in hwmon.
2. Run loop for port creation over maximum port counter, otherwise
in some split configuration with holes, some last modules can be
missed.
0032-mellanox-platform-Backporting-Melanox-drivers-from-v.patch :
This patch is required for new Mellanox systems and also contains
bugfixes. Patch contains backporting for the next drivers:
drivers/net/ethernet/mellanox/mlxsw/mlxsw_minimal;
drivers/platform/x86/mlx-platform;
drivers/platform/mellanox/mlxreg-hotplug;
drivers/hwmon/mlxreg-fan
> Add patches for Mellanox:

- packages/platforms/accton/x86-64/as5916-54x/platform-config/r1/src/python/x86_64_accton_as5916_54x_r1/__init__.py
- packages/platforms/accton/x86-64/as5916-54xm/platform-config/r0/src/python/x86_64_accton_as5916_54xm_r0/__init__.py
- packages/platforms/accton/x86-64/as7326-56x/platform-config/r0/src/python/x86_64_accton_as7326_56x_r0/__init__.py
- packages/platforms/accton/x86-64/as7726-32x/platform-config/r0/src/python/x86_64_accton_as7726_32x_r0/__init__.py
Fix ir3570a i2c casue to read eeprom fail
>  Fix ir3570a i2c casue to read eeprom fail

- packages/base/any/onlp/src/onlp/module/src/platform_manager.c
- packages/platforms/ingrasys/x86-64/s9180-32x/onlp/builds/x86_64_ingrasys_s9180_32x/module/src/sysi.c
This commit including following changes :
1. add 2 functions (onlp_sysi_onie_data_free, onlp_sysi_platform_info_free) in sysi.c to free allocated memory for s9180 platform
2.  add onlp_sys_info_free after invoking onlp_sys_info_get to free allocated memory in platform_manager.c
> Fix onlpd memory leakage for s9180 bmc enabled platform

- packages/platforms/accton/x86-64/as5916-54xks/modules/builds/x86-64-accton-as5916-54xks-psu.c
- packages/platforms/accton/x86-64/as5916-54xks/onlp/builds/x86_64_accton_as5916_54xks/module/src/psui.c
1. Fix PSU incorrect serial number/model name issue.
2. Add IPMI retry mechanism in psu driver
> [as5916-54xks] Fix PSU incorrect serial number/model name issue

- packages/base/any/kernels/4.14-lts/patches/0003-drivers-net-ethernet-broadcom-tg3.patch
Original patch makes  management port not link up on some platforms. 
Fix that problem and move changes to kernel paramters.
Signed-off-by: roylee123 <roy_lee@accton.com>
> [Accton]Fix problem for management port not link up.

- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/chassisi.c
- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/platform_lib.c
Added **bmc_tty_init** function call inside **bmc_send_command** function,
as it is mandatory to login BMC prompt once, before sending commands to BMC.
Where as removed **bmc_tty_init** function in chassisi.c, as functions in chassisi.c are called by specifically interested application only and in this case **bmc_tty_init** will never be called.
> [wedge100bf-32x] Added bmc_tty_init() function call inside bmc_send_command function

- packages/base/any/kernels/4.9-lts/patches/0033-mlxsw-minimal-Provide-optimization-for-module-number.patch
- packages/base/any/kernels/4.9-lts/patches/0034-mlxsw-minimal-Add-validation-for-FW-version.patch
- packages/base/any/kernels/4.9-lts/patches/0035-mlxsw-core-Extend-QSFP-EEPROM-supported-size-for-eth.patch
- packages/base/any/kernels/4.9-lts/patches/series
Mellanox: extend size of QSFP EEPROM for the cable type SSF8436, SFF8636 from 256 to 612 bytes in order to make available all the pages.
> [Mellanox]  Extend size of QSFP EEPROM for the cable type SSF8436, SFF8636 from 256 to 612 bytes

- packages/platforms/accton/x86-64/as5916-54xks/platform-config/r0/src/lib/x86-64-accton-as5916-54xks-r0.yml
Fix fault of DMA Read by turning off intel_iommu at kernel.
Signed-off-by: roylee123 <roy_lee@accton.com>
> [Accton] as5916-54xks, fix fault of DMA Read by turning off intel_iommu at kernel.

- packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/sysi.c
- packages/platforms/accton/x86-64/as9716_32d/platform-config/r0/src/python/x86_64_accton_as9716_32d_r0/__init__.py
New board eeprom addr is 0x57. Old board is 0x56. Modify code to support two board eeprom-sysfs.
> Add support 0x57 and 0x56 eeprom sysfs for as9716

- make/onlp.version
- packages/base/any/onlp/builds/onlp-platform-defaults/Makefile
- packages/base/any/onlp/builds/onlp-platform/Makefile
- packages/base/any/onlp/builds/onlp/Makefile
- packages/base/any/onlp/builds/platform/libonlp-platform.mk
ONLP libraries expose some symbols from utilities (e.g., `cJSON_*`) as global binding.
Those symbols cause unexpected behavior to the binary which links to it (libonlp*.so).
> Hide non-onlp symbols (ONLPv2)

- packages/platforms/inventec/x86-64/d10056/modules/PKG.yml
- packages/platforms/inventec/x86-64/d10056/modules/builds/Makefile
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/Makefile
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/gpio-ich.c
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/inv_platform.c
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/inv_psoc.c
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/inv_swps.h
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/inv_vpd.c
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/transceiver.c
- packages/platforms/inventec/x86-64/d10056/modules/builds/src/transceiver.h
- packages/platforms/inventec/x86-64/d10056/onlp/builds/x86_64_inventec_d10056/module/src/sfpi.c
- packages/platforms/inventec/x86-64/d10056/onlp/builds/x86_64_inventec_d10056/module/src/sysi.c
- packages/platforms/inventec/x86-64/d10056/platform-config/r0/src/lib/x86-64-inventec-d10056-r0.yml
- packages/platforms/inventec/x86-64/d10056/platform-config/r0/src/python/x86_64_inventec_d10056_r0/__init__.py
the detail of fixes this time are listed below
- Upgrade kernel to 4.14
- ONLP debug
1) Fix wrong rxlos and reset state value
2) Use inv_eeprom to read eeprom data
And attached is the test report
[d10056_upstream.pdf](https://github.com/opencomputeproject/OpenNetworkLinux/files/4039340/d10056_upstream.pdf)
> Upgrade kernel to 4.14 and debug ONLP for D10056

- builds/any/rootfs/jessie/standard/standard.yml
- builds/any/rootfs/jessie/systemd/overlay/sbin/init
- builds/any/rootfs/jessie/sysvinit/overlay/etc/inittab
With this pull request we fix #659 Jessie: Boot.d scripts not being run.
We just tested it with ingrasys-s9180-32x-r0.
> fixed #659 Jessie: Boot.d scripts not being run

- packages/platforms/accton/x86-64/asxvolt16/platform-config/r0/src/python/x86_64_accton_asxvolt16_r0/__init__.py
IR3507A chip will cause i2c read fail on block mode when board eeprom 16th offset's value is 0x8.
So disable it to avoid cause i2c block mode fail.
> [asxvolt16]:Fix ir3507a issue

- packages/platforms/quanta/any/src/quanta_sys_eeprom/module/src/eeprom.c
add support for onie-eeprom diag version compatible with ascii format
legacy format is four bytes digits, which means diag version(2 bytes) and platform(2 bytes)
for better compatibility for onie eeprom definition, quanta use this field as ascii format
> [quanta] modify qunata_eeprom for ascii format compatibility

- packages/platforms/alphanetworks/x86-64/stx60d0-062f/onlp/builds/x86_64_alphanetworks_stx60d0_062f/module/src/fani.c
- packages/platforms/alphanetworks/x86-64/stx60d0-062f/onlp/builds/x86_64_alphanetworks_stx60d0_062f/module/src/sysi.c
- packages/platforms/alphanetworks/x86-64/stx60d0-062f/platform-config/r0/src/lib/x86-64-alphanetworks-stx60d0-062f-r0.yml
[stx60d0-062f] Modify to use ttyS1 for sync with BIOS and ONIE, and FAN management mechanism is only controlled by BMC.
> stx60d0-062f issue fix

- packages/platforms/accton/x86-64/as7315-27xb/onlp/builds/x86_64_accton_as7315_27xb/module/src/psui.c
- packages/platforms/accton/x86-64/as7315-27xb/onlp/builds/x86_64_accton_as7315_27xb/module/src/sfpi.c
- packages/platforms/accton/x86-64/as7315-27xb/onlp/builds/x86_64_accton_as7315_27xb/module/src/sysi.c
Signed-off-by: roy_lee <roy_lee@accton.com>
1. Add aim_free() after called onlp_file_read_str() to avoid memory leaking.
2.  After called onlp_file_read_str(), call aim_free() if and only the pointer is not NULL.
3. Remove unnecessary checking on fan control.
> [platform/accton] as7315-27xb: fix memory leaking

- packages/base/all/vendor-config-onl/src/python/onl/platform/base.py
Signed-off-by: roy_lee <roy_lee@edge-core.com>
Add OnlPlatformPortConfig for as7936-22xke, the PortConfig_10x400_18x100_2x10.
> [platform/accton] as7936-22xke: Add missed OnlPlatformPortConfig

- packages/platforms/accton/x86-64/minipack/modules/builds/minipack_psensor.c
- packages/platforms/accton/x86-64/minipack/onlp/builds/x86_64_accton_minipack/module/src/platform_lib.c
- packages/platforms/accton/x86-64/minipack/platform-config/r0/src/python/x86_64_accton_minipack_r0/__init__.py
BMC allows root user to change it's password through ipmitool cmd or lan link.
For that, ONL driver needs new password to access BMC as well.
User is responsible to write explicit password to /etc/bmcpwd, for driver can log into BMC.
> [device/accton] Minipack: work with bmc which changes default password

- packages/platforms/accton/x86-64/as9716_32d/onlp/builds/x86_64_accton_as9716_32d/module/src/sysi.c
When fan is plug out, fan speed will be set to 100%.
When plug in back fan, fan speed should be set to according to thermal plan .
> [AS9716]Fix thermal plan issue

- packages/platforms/inventec/x86-64/d6356/modules/builds/src/inv_cpld.c
The compiler flag `-Werror` looks like it was recently turned on for this platform which has made this a build failure on stretch using:
```
make VERSION=9 docker
```
> Fixed build issue on stretch in inventec d6356

- docker/tools/onlbuilder
Signed-off-by: Steven Noble <snoble@sonn.com>
> Move onlbuilder for debian 9 to dentproject v1.8

- .gitmodules
By request all submodules are being moved off of the opennetworklinux/floodlight repositories.
Signed-off-by: Steven Noble <snoble@sonn.com>
> Update submodules to point to opennetlinux github

- packages/platforms/delta/x86-64/ag9032v2/platform-config/r0/src/python/x86_64_delta_ag9032v2_r0/__init__.py
Add kernel modules probe to platform init script. [ag9032v2]
1. i2c_ismt
2. at24
> [ag9032v2] Add kernel modules probe to platform init script.

- packages/platforms/accton/x86-64/as4630-54pe/modules/builds/x86-64-accton-as4630-54pe-cpld.c
- packages/platforms/accton/x86-64/as4630-54pe/onlp/builds/x86_64_accton_as4630_54pe/module/src/sfpi.c
Validate tx_disable function of 4 SFP+ ports and test by 
Change tx_disable by 'onlp_sfpi_control_set()' and read by `onlpdump`.
Signed-off-by: roy_lee <roy_lee@edge-core.com>
Partial test log: 
root@localhost:~# onlpdump
....
SFPs:
Presence Bitmap: 48 49 51
RX_LOS Bitmap: 48 49 50 51
Port 48: Present, Status = 0x00000014 [ RX_LOS,TX_DISABLE ]
eeprom:
....
Port 49: Present, Status = 0x00000004 [ RX_LOS ]
eeprom:
....
> [device/accton] AS4630-54PE: Validate tx_disable function of 4 SFP+ ports.

- packages/base/all/vendor-config-onl/src/python/onl/platform/base.py
- packages/platforms/accton/x86-64/as4630-54pe/platform-config/r0/src/python/x86_64_accton_as4630_54pe_r0/__init__.py
The correct port configuration of as4630_54pe is as below:
root@localhost:~# onl-platform-show
Model: AS4630-54PE
Manufacturer: Accton
Ports: 54 (48x1 + 4x25 + 2x100)
> [as4630_54pe] Fix platform port config

- packages/platforms/accton/x86-64/as5916-26xb/onlp/builds/x86_64_accton_as5916_26xb/module/src/psui.c
- packages/platforms/accton/x86-64/as5916-54xks/onlp/builds/x86_64_accton_as5916_54xks/module/src/psui.c
- packages/platforms/accton/x86-64/as5916-54xl/onlp/builds/x86_64_accton_as5916_54xl/module/src/psui.c
- packages/platforms/accton/x86-64/as7315-27xb/onlp/builds/x86_64_accton_as7315_27xb/module/src/psui.c
- packages/platforms/accton/x86-64/as7315-27xb/onlp/builds/x86_64_accton_as7315_27xb/module/src/sfpi.c
- packages/platforms/accton/x86-64/as7316-26xb/onlp/builds/x86_64_accton_as7316_26xb/module/src/psui.c
- packages/platforms/accton/x86-64/as7712-32x/onlp/builds/x86_64_accton_as7712_32x/module/src/platform_lib.c
- packages/platforms/accton/x86-64/asgvolt64/onlp/builds/x86_64_accton_asgvolt64/module/src/psui.c
The memory leak occurs on several accton platforms. It occurs on switches
that do not have PSU1 present. The memory leak is caused due to an allocated,
but empty string being returned from the onlp_file_read_str() function. The
code calling the onlp_file_read_str() function would free the returned
allocated string only if the string was not NULL and not empty.
#822 contain 7 platforms with memory leak:
as5916-26xb / as5916-54xks / as5916-54xl / as7315-27xb / as7316-26xb / as7712-32x / asgvolt64
#824 is for the rest platforms which also use onlp_file_read_str() but not release memory precisely:
as5835-54t / as5835-54x / as5912-54x / as5916-54xm / as7312-54x / as7312-54xs / as9926-24d
> [Accton] Fix memory leak if PSU1 is not present

- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/sysi.c
- packages/platforms/accton/x86-64/as7326-56x/platform-config/r0/src/python/x86_64_accton_as7326_56x_r0/__init__.py
Due to the HW change, make eeprom access compatible with both new and
old conditions.
Signed-off-by: Sean Wu <sean_wu@edge-core.com>
> [as7326-56x] support eeprom at addr 0x56 and 0x57

- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/fani.c
- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/ledi.c
- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/platform_lib.c
- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/platform_lib.h
- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/psui.c
- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/sfpi.c
- packages/platforms/accton/x86-64/wedge100bf-32x/onlp/builds/x86_64_accton_wedge100bf_32x/module/src/thermali.c
There are many error can be seen at  /var/log/onlpd.log a while after boot-up.
Most of error are caused by parted of BMC tty's response.
To solve that, add retries of whole transaction to BMC, it can give a clear /var/log/onlpd.log over-night .
But it still cannot guarantee no error while BMC is busy. 
It's a trade-off between response time and accuration.
Signed-off-by: roy_lee <roy_lee@edge-core.com>
> [device/accton] wedge100bf-32x: Fix some onlpi errors at onlpd.log

- packages/platforms/accton/x86-64/as5916-54xl/modules/builds/x86-64-accton-as5916-54xl-fan.c
- packages/platforms/accton/x86-64/as5916-54xl/onlp/builds/x86_64_accton_as5916_54xl/module/src/fani.c
- packages/platforms/accton/x86-64/as5916-54xl/onlp/builds/x86_64_accton_as5916_54xl/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as5916-54xl/onlp/builds/x86_64_accton_as5916_54xl/module/src/sysi.c
Each fan tray has two fans (front+rear) inside. Display rear fan info additionally due to customer's request.
> [AS5916-54XL] display rear fans info

- packages/platforms/accton/x86-64/as7326-56x/modules/builds/x86-64-accton-as7326-56x-psu.c
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/fani.c
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/platform_lib.c
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/psui.c
- packages/platforms/accton/x86-64/as7716-32x/modules/builds/x86-64-accton-as7716-32x-psu.c
- packages/platforms/accton/x86-64/as7716-32x/onlp/builds/x86_64_accton_as7716_32x/module/src/fani.c
- packages/platforms/accton/x86-64/as7716-32x/onlp/builds/x86_64_accton_as7716_32x/module/src/platform_lib.c
- packages/platforms/accton/x86-64/as7716-32x/onlp/builds/x86_64_accton_as7716_32x/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as7716-32x/onlp/builds/x86_64_accton_as7716_32x/module/src/psui.c
- packages/platforms/accton/x86-64/as7726-32x/modules/builds/x86-64-accton-as7726-32x-psu.c
- packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/fani.c
- packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/platform_lib.c
- packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as7726-32x/onlp/builds/x86_64_accton_as7726_32x/module/src/psui.c
Support ACBEL PSUs because of the part replacement.
- Models: as7716-32x, as7726-32x, as7326-56x
> [Accton] Support ACBEL FSF019 PSUs

- packages/platforms/accton/x86-64/wedge100bf-65x/onlp/builds/x86_64_accton_wedge100bf_65x/module/src/fani.c
- packages/platforms/accton/x86-64/wedge100bf-65x/onlp/builds/x86_64_accton_wedge100bf_65x/module/src/ledi.c
- packages/platforms/accton/x86-64/wedge100bf-65x/onlp/builds/x86_64_accton_wedge100bf_65x/module/src/platform_lib.c
- packages/platforms/accton/x86-64/wedge100bf-65x/onlp/builds/x86_64_accton_wedge100bf_65x/module/src/platform_lib.h
- packages/platforms/accton/x86-64/wedge100bf-65x/onlp/builds/x86_64_accton_wedge100bf_65x/module/src/psui.c
- packages/platforms/accton/x86-64/wedge100bf-65x/onlp/builds/x86_64_accton_wedge100bf_65x/module/src/sfpi.c
- packages/platforms/accton/x86-64/wedge100bf-65x/onlp/builds/x86_64_accton_wedge100bf_65x/module/src/thermali.c
To prevent error result from BMC message broken,
1. Remain wait time (55000us) and retry more times (20 times)
These are experimental results.
If wait time is over 80000us, it will cause onlpd for increasing
CPU usage.
Verified by overnight busy run and no error at /var/log/onlpd.log.
2. Clear tty rx buffer before transaction.
3. PSUs should locate at 0x5a and 0x59, instead of 0x59 and 0x5a.
4. Print PSU's model_name and serial if it's present but not powered.
5. Set i2c mux to PSUs are both opened. It makes no conflict for
their addresses diff.
6. For individual onlp API can be called after its own init() is run.
Signed-off-by: Jake Lin <jake_lin@edge-core.com>
> [accton/wedge100bf-65x] Fix some onlpi errors at onlpd.log

- packages/base/any/kernels/modules/ym2651y.c
- packages/platforms/accton/x86-64/as7315-27xb/modules/builds/x86-64-accton-as7315-27xb-psu.c
- packages/platforms/accton/x86-64/as7315-27xb/onlp/builds/x86_64_accton_as7315_27xb/module/src/psui.c
To support as7315-27xb AC PSU,
1. Add new PSU model information to ym2651y.c for V_IN, I_IN and P_IN.
2. Add some conditions for ym2651y.c.
3. Add new PSU model information to x86-64-accton-as7315-27xb-psu.c.
4. Modify psui.c to support onlpd showing AC PSU state.
Signed-off-by: Jake Lin <jake_lin@edge-core.com>
> [accton/as7315-27xb] Support AC PSU on ONL

- packages/platforms/accton/x86-64/as9926-24d/onlp/builds/x86_64_accton_as9926_24d/module/src/fani.c
- packages/platforms/accton/x86-64/as9926-24d/onlp/builds/x86_64_accton_as9926_24d/module/src/platform_lib.c
- packages/platforms/accton/x86-64/as9926-24d/onlp/builds/x86_64_accton_as9926_24d/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as9926-24d/onlp/builds/x86_64_accton_as9926_24d/module/src/psui.c
The output of onlpdump is as below:
psu @ 1 = {
Description: PSU-1
Model:  FSJ033-610G
SN:     FSJ033202100000303
Status: 0x00000001 [ PRESENT ]
Caps:   0x000001fc [ DC48,VIN,VOUT,IIN,IOUT,PIN,POUT ]
Vin:    54187
Vout:   12031
Iin:    2382
Iout:   7500
Pin:    121750
Pout:   87000
fan @ 7 = {
Description: PSU 1 - Fan 1
Status: 0x00000009 [ PRESENT,F2B ]
Caps:   0x00000030 [ GET_RPM,GET_PERCENTAGE ]
RPM:    14976
Per:    58
Model:  NULL
SN:     NULL
}
thermal @ 11 = {
Description: PSU-1 Thermal Sensor 1
Status: 0x00000001 [ PRESENT ]
Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
Temperature: 29000
thresholds = {
Warning: 74000
Error: 80000
Shutdown: 84000
}
}
thermal @ 12 = {
Description: PSU-1 Thermal Sensor 2
Status: 0x00000001 [ …
> [as9926-24d] Support FSJ033-610G DC PSU

- packages/platforms/accton/x86-64/as7816-64x/onlp/builds/x86_64_accton_as7816_64x/module/src/sysi.c
Update AS7816-64X thermal policy according to the new spec from HW guys.
Verified with onlps, test log: [thermal_plan_test_on_DUT.log](https://github.com/opencomputeproject/OpenNetworkLinux/files/7568690/thermal_plan_test_on_DUT.log)
Signed-off-by: Sean Wu sean_wu@edge-core.c
> Update AS7816-64X thermal policy

- packages/platforms/accton/x86-64/as7816-64x/onlp/builds/x86_64_accton_as7816_64x/module/src/psui.c
The "miin" is not assigned after reading from PSU.
Set the value to fix zero input current.
psu @ 1 = {
Description: PSU-2
Model:  DPS-850A
SN:     JKFD92L000T
Status: 0x00000001 [ PRESENT ]
Caps:   0x000001f9 [ AC,VIN,VOUT,IIN,IOUT,PIN,POUT ]
Vin:    117876
Vout:   12046
Iin:    873
Iout:   7859
Pin:    103500
Pout:   94625
Signed-off-by: brandonchuang <brandon_chuang@edge-core.com>
> [Edgecore][as7816-64x] Correct the value of input current

- builds/any/rootfs/jessie/standard/standard.yml
- builds/any/rootfs/stretch/standard/standard.yml
- builds/any/rootfs/wheezy/standard/standard.yml
https://mirrors.edge.kernel.org/debian/dists/ not support jessie.
Workaround URL is http://archive.debian.org/debian/dists/ and test OK.
> Change DEBIAN_MIRROR site to fix build issue

- packages/platforms/accton/x86-64/as5835-54x/onlp/builds/x86_64_accton_as5835_54x/module/src/platform_lib.c
1. Fixed the wrong fan dir node of psu2.
> [Edgecore][AS5835-54X] Fixed the issue that failed to detect PSU module on PSU SLOT-2 without PSU SLOT-1

- packages/platforms/accton/x86-64/as7326-56x/modules/builds/x86-64-accton-as7326-56x-fan.c
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/fani.c
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as7326-56x/onlp/builds/x86_64_accton_as7326_56x/module/src/sysi.c
1. We enable fan-watchdog to enhance fan controller.
2. Set the fan max PWM to 100%
> [Edgecore][AS7326-56X] Enhance fan controller to execute fan-watchdog

- packages/platforms/accton/x86-64/as7326-56x/platform-config/r0/src/python/x86_64_accton_as7326_56x_r0/__init__.py
The port occur failed because the last port_name is no set. Modify the init.py to fix the issus
Signed-off-by: Willy Liu <willy_liu@edge-core.com>
> [Edgecore][as7326-56x] Fix the last port issus

- packages/base/any/kernels/modules/ym2651y.c
- packages/platforms/accton/x86-64/as5912-54x/modules/builds/x86-64-accton-as5912-54x-psu.c
- packages/platforms/accton/x86-64/as5912-54x/onlp/builds/x86_64_accton_as5912_54x/module/src/platform_lib.c
- packages/platforms/accton/x86-64/as5912-54x/onlp/builds/x86_64_accton_as5912_54x/module/src/psui.c
1. Add node of psu product name.
2. Access this node to get the completed PSU product name
3. Add Delta AC 650W PSU
4. remove the redundant space of output
Signed-off-by: Willy Liu <willy_liu@edge-core.com>
> [Edgecore][AS5912-54X] Support Delta AC 650W PSU

- packages/platforms/accton/x86-64/as4630-54te/modules/builds/x86-64-accton-as4630-54te-psu.c
- packages/platforms/accton/x86-64/as4630-54te/onlp/builds/x86_64_accton_as4630_54pe/module/src/fani.c
- packages/platforms/accton/x86-64/as4630-54te/onlp/builds/x86_64_accton_as4630_54pe/module/src/platform_lib.c
- packages/platforms/accton/x86-64/as4630-54te/onlp/builds/x86_64_accton_as4630_54pe/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as4630-54te/onlp/builds/x86_64_accton_as4630_54pe/module/src/psui.c
Modify driver and onlp to support YM-1151F
The airflow direction is front to back
The output of onlpdump is as follows:
psu @ 1 = {
Description: PSU-1
Model:  YM-1151F-A01R
SN:     SA03A1442209007283
Status: 0x00000001 [ PRESENT ]
Caps:   0x00000151 [ AC,VOUT,IOUT,POUT ]
Vin:    0
Vout:   12015
Iin:    0
Iout:   2113
Pin:    0
Pout:   25000
fan @ 4 = {
Description: PSU 1 - Fan 1
Status: 0x00000009 [ PRESENT,F2B ]
Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
RPM:    9600
Per:    37
Model:  NULL
SN:     NULL
}
thermal @ 5 = {
Description: PSU-1 Thermal Sensor 1
Status: 0x00000001 [ PRESENT ]
Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
Temperature: 36000
thresholds = {
Warning: 45000
Error: 50000
Shutdown: 55000
}
} …
> [Edgecore][as4630_54te] Support YM-1151F power supply

- packages/platforms/accton/x86-64/as7926-40xfb/modules/builds/x86-64-accton-as7926-40xfb-cpld.c
- packages/platforms/accton/x86-64/as7926-40xfb/modules/builds/x86-64-accton-as7926-40xfb-fan.c
- packages/platforms/accton/x86-64/as7926-40xfb/modules/builds/x86-64-accton-as7926-40xfb-leds.c
- packages/platforms/accton/x86-64/as7926-40xfb/modules/builds/x86-64-accton-as7926-40xfb-psu.c
- packages/platforms/accton/x86-64/as7926-40xfb/modules/builds/x86-64-accton-as7926-40xfb-sys.c
- packages/platforms/accton/x86-64/as7926-40xfb/modules/builds/x86-64-accton-as7926-40xfb-thermal.c
- packages/platforms/accton/x86-64/as7926-40xfb/onlp/builds/x86_64_accton_as7926_40xfb/module/src/fani.c
- packages/platforms/accton/x86-64/as7926-40xfb/onlp/builds/x86_64_accton_as7926_40xfb/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as7926-40xfb/onlp/builds/x86_64_accton_as7926_40xfb/module/src/sfpi.c
- packages/platforms/accton/x86-64/as7926-40xfb/onlp/builds/x86_64_accton_as7926_40xfb/module/src/sysi.c
- packages/platforms/accton/x86-64/as7926-40xfb/onlp/builds/x86_64_accton_as7926_40xfb/module/src/thermali.c
- packages/platforms/accton/x86-64/as7926-40xfb/platform-config/r0/src/python/x86_64_accton_as7926_40xfb_r0/__init__.py
- Remove i2c mux 0x72 which is used by BMC
- Use GNU indent to format peripheral drivers
- Add BMC detection in __init__.py
- Add ONLP_SFP_CONTROL_RESET in sfp.py
> [Edgecore][as7926_40xfb] Update drivers/API to match latest BMC firmware

- packages/platforms/accton/x86-64/as4630-54te/platform-config/r0/src/lib/x86-64-accton-as4630-54te-r0.yml
Disable intel_iommu to prevent below error messages:
[10672.868940] DMAR: [DMA Write] Request device [00:12.0] fault addr 0 [fault reason 05] PTE Write access is not set
[10672.869183] DMAR: DRHD: handling fault status reg 2
[10672.869188] DMAR: [DMA Write] Request device [00:12.0] fault addr 0 [fault reason 05] PTE Write access is not set
[10672.869443] DMAR: DRHD: handling fault status reg 2
[10672.869448] DMAR: [DMA Write] Request device [00:12.0] fault addr 0 [fault reason 05] PTE Write access is not set
[10672.870074] DMAR: DRHD: handling fault status reg 2
[10677.928602] dmar_fault: 2474 callbacks suppressed
[10677.928604] DMAR: DRHD: handling fault status reg 2
> [as4630_54te] Fix the error "PTE Write access is not set"

- Makefile
Debian 9 (and soon 10) will be the default build version.
> Update Makefile to default to Debian 9

- packages/platforms/accton/x86-64/as4630-54pe/onlp/builds/x86_64_accton_as4630_54pe/module/src/sfpi.c
When Merging #862 there was a duplicate case statement in sfpi.c line 236 : 
`         case ONLP_SFP_CONTROL_TX_DISABLE:`
This PR removes the extra lines and fixes build issues.
> Fix for duplicate case introduced by #862 as4630-54p3 sfpi.c

- packages/platforms/accton/x86-64/as7535-28xb/modules/builds/x86-64-accton-as7535-28xb-thermal.c
- packages/platforms/accton/x86-64/as7535-28xb/onlp/builds/x86_64_accton_as7535_28xb/module/src/platform_lib.c
- packages/platforms/accton/x86-64/as7535-28xb/onlp/builds/x86_64_accton_as7535_28xb/module/src/platform_lib.h
- packages/platforms/accton/x86-64/as7535-28xb/onlp/builds/x86_64_accton_as7535_28xb/module/src/psui.c
- packages/platforms/accton/x86-64/as7535-28xb/onlp/builds/x86_64_accton_as7535_28xb/module/src/sysi.c
- packages/platforms/accton/x86-64/as7535-28xb/onlp/builds/x86_64_accton_as7535_28xb/module/src/thermali.c
[Edgecore][AS7535-28XB] Support R01 version DUT with 6 thermals and R02 version DUT with 8 thermals
1.  It support R01 version  DUT with 6 thermals and R02 version  DUT with 8 thermals
2. Modify thermal name
3. Add the new thermals sysfs
4. Add the function to get pcb id
> [Edgecore][AS7535-28XB] Support R01 version DUT with 6 thermals and R02 version DUT with 8 thermals

- packages/platforms/accton/armxx/arm-accton-as4610/arm_accton_as4610/module/src/ledi.c
Fix two issues found in the LED platform code:
* LED values > 9 were not properly handled, causing LED states improperly reported.
* PATH name buffer used for storing sysfs paths was insufficiently sized, causing buffer overruns which may trigger stack protection.
For details see the individual commit messages.
> accton-as4610: LED handling fixes

- packages/platforms/accton/x86-64/as7926-40xfb/onlp/builds/x86_64_accton_as7926_40xfb/module/src/ledi.c
The locator LED color is changed from green blinking to blue blinking.
Modify ledi.c to fit latest hardware specification.
> [Edgecore][as7926_40xfb] Revise locator LED definition

- packages/platforms/accton/x86-64/as4630-54pe/onlp/builds/x86_64_accton_as4630_54pe/module/src/sfpi.c
1. Add controlling function of QSFP Tx disable
2. To get and set qsfp tx disable by accessing qsfp eeprom
> [Edgecore][AS4630-54PE] Add controlling function of QSFP Tx disable

- packages/platforms/accton/armxx/arm-accton-as4610/modules/accton_as4610_cpld.c
- packages/platforms/accton/armxx/arm-accton-as4610/modules/accton_as4610_fan.c
- packages/platforms/accton/armxx/arm-accton-as4610/modules/accton_as4610_leds.c
Properly let the CPLD driver manage the LED and CPLD platform devices instead of registering them always in their respective modules.
This avoids registering devices on platforms without the CPLD present, introduces proper ordering of registering the platform devices only after the CPLD driver has finished initializing, and simplifies the drivers significantly.
To make this properly work, also fix the module device table for the FAN driver, and add one for the LED driver.
> Accton AS4610: let the CPLD driver handle sub devices

- packages/platforms/accton/x86-64/as9817-64/src/modules/x86-64-accton-as9817-64-fan.c
- packages/platforms/accton/x86-64/as9817-64/src/modules/x86-64-accton-as9817-64-fpga.c
- packages/platforms/accton/x86-64/as9817-64/src/modules/x86-64-accton-as9817-64-i2c-ocores.c
- packages/platforms/accton/x86-64/as9817-64/src/modules/x86-64-accton-as9817-64-leds.c
- packages/platforms/accton/x86-64/as9817-64/src/modules/x86-64-accton-as9817-64-psu.c
- packages/platforms/accton/x86-64/as9817-64/src/modules/x86-64-accton-as9817-64-sys.c
- packages/platforms/accton/x86-64/as9817-64/src/modules/x86-64-accton-as9817-64-thermal.c
1. the pcie addr of spi_busy_reg becomes the current bar0 addr plus spi_busy_reg offset, instead of a fixed addr.
> [Edgecore][as9817-64d][as9817-64o] Fixed spi_busy_reg's pcie addr issue
